# 24. Agreement-gated Comparable after 17

23번 comparable sales 신호는 Fold2에서는 크게 먹혔지만 Fold3에서 깨졌습니다.

이번 실험은 comparable sales를 단독 보정으로 쓰지 않고, 17의 HistGB residual 방향과 같은 방향일 때만 제한적으로 적용합니다.

- 기준 예측: 17
- 추가 신호: comparable sales prediction
- 적용 조건: comparable gap과 17 residual-stack gap의 방향이 일치하는 row만
- 과도한 이동 방지: correction cap 적용
- OOF 기준 Fold2/Fold3 모두 개선될 때만 제출 파일 생성

In [1]:
from pathlib import Path
import json
import warnings

import numpy as np
import pandas as pd
from IPython.display import display

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 180)
pd.set_option('display.float_format', lambda x: f'{x:,.6f}')

candidates = [Path.cwd(), Path.cwd().parent]
PROJECT_ROOT = next((p for p in candidates if (p / 'data').exists()), None)
if PROJECT_ROOT is None:
    raise FileNotFoundError('프로젝트 루트를 찾을 수 없습니다.')

# 23번을 재현해 comparable cache와 17 OOF/test prediction을 가져옵니다.
# 23 자체는 안정 조건 미통과 시 제출 파일을 만들지 않습니다.
nb23 = json.loads((PROJECT_ROOT / 'notebooks' / '23_comparable_sales_after17.ipynb').read_text())
code23 = ''.join(nb23['cells'][1]['source'])
ns23 = {}
exec(code23, ns23)

rmse = ns23['rmse']
oof = ns23['oof'].copy()
folds = ns23['folds']
test = ns23['test']
sample_submission = ns23['sample_submission']
SUBMISSION_DIR = ns23['SUBMISSION_DIR']
test_frame = ns23['test_frame'].copy()
inner15 = ns23['inner15']
test_pred17 = ns23['test_pred17']
comparable_predict = ns23['comparable_predict']
comp_cache = ns23['comp_cache']
GATES = ns23['GATES']
train = ns23['train']

pred17_all = oof['Pred17'].to_numpy()
pred15_all = oof['Pred15'].to_numpy()
y_all = oof['Target'].to_numpy()
hist_gap_all = pred17_all - pred15_all
base17_rmse = rmse(y_all, pred17_all)
print(f'17 pooled RMSE: {base17_rmse:,.6f}')

ALPHAS = [0.02, 0.03, 0.05, 0.08]
CAPS = [300, 500, 800, 1200, 1800]
HIST_MIN_ABS = [0, 10, 25, 50]

rows = []
detail_tables = {}

for comp_key, comp_pred in comp_cache.items():
    scope, prior, top_k = comp_key
    comp_gap_all = comp_pred - pred17_all
    for gate_name, gate_col, gate_quantile in GATES:
        for alpha in ALPHAS:
            for cap in CAPS:
                for hist_min_abs in HIST_MIN_ABS:
                    pred24 = pred17_all.copy()
                    detail = []
                    offset = 0
                    for fold in folds:
                        frame = oof.loc[oof['Fold'] == fold].copy()
                        n = len(frame)
                        y = frame['Target'].to_numpy()
                        pred17 = frame['Pred17'].to_numpy()
                        comp_gap = comp_gap_all[offset:offset+n]
                        hist_gap = hist_gap_all[offset:offset+n]
                        if fold == 1:
                            mask = np.zeros(n, dtype=bool)
                        else:
                            agree = (comp_gap * hist_gap) > 0
                            strong_enough = np.abs(hist_gap) >= hist_min_abs
                            bounded = np.abs(comp_gap) <= cap * 6  # 극단 comparable outlier만 제거
                            if gate_col is None:
                                gate_mask = np.ones(n, dtype=bool)
                            else:
                                fit_hist = oof.loc[oof['Fold'] < fold].copy()
                                threshold = fit_hist[gate_col].quantile(gate_quantile)
                                gate_mask = frame[gate_col].to_numpy() <= threshold
                            mask = agree & strong_enough & bounded & gate_mask
                        clipped_gap = np.clip(comp_gap, -cap, cap)
                        pred_fold = pred17.copy()
                        pred_fold[mask] = np.clip(pred17[mask] + alpha * clipped_gap[mask], 0, None)
                        pred24[offset:offset+n] = pred_fold
                        detail.append({
                            'Fold': int(fold),
                            'Rows': n,
                            '17_RMSE': rmse(y, pred17),
                            '24_RMSE': rmse(y, pred_fold),
                            '24_vs_17_Improvement': rmse(y, pred17) - rmse(y, pred_fold),
                            'Applied_Rows': int(mask.sum()),
                            'Mean_abs_move': float(np.mean(np.abs(pred_fold - pred17))),
                        })
                        offset += n
                    detail = pd.DataFrame(detail)
                    eligible = detail.loc[detail['Fold'] > 1]
                    key = (scope, prior, top_k, gate_name, alpha, cap, hist_min_abs)
                    detail_tables[key] = detail
                    rows.append({
                        'Scope': scope,
                        'Prior': prior,
                        'TopK': top_k,
                        'Gate': gate_name,
                        'Alpha': alpha,
                        'Cap': cap,
                        'HistMinAbs': hist_min_abs,
                        '17_Pooled_RMSE': base17_rmse,
                        '24_Pooled_RMSE': rmse(y_all, pred24),
                        'Pooled_Improvement': base17_rmse - rmse(y_all, pred24),
                        'Improved_Eligible_Folds': int((eligible['24_vs_17_Improvement'] > 0).sum()),
                        'Worst_Eligible_Improvement': eligible['24_vs_17_Improvement'].min(),
                        'Fold2_Improvement': detail.loc[detail['Fold'] == 2, '24_vs_17_Improvement'].iloc[0],
                        'Fold3_Improvement': detail.loc[detail['Fold'] == 3, '24_vs_17_Improvement'].iloc[0],
                        'Mean_abs_move': detail['Mean_abs_move'].mean(),
                        'Applied_Rows_F2': detail.loc[detail['Fold'] == 2, 'Applied_Rows'].iloc[0],
                        'Applied_Rows_F3': detail.loc[detail['Fold'] == 3, 'Applied_Rows'].iloc[0],
                    })

summary = pd.DataFrame(rows).sort_values(
    ['Pooled_Improvement', 'Worst_Eligible_Improvement', 'Fold3_Improvement'],
    ascending=[False, False, False],
).reset_index(drop=True)
display(summary.head(40))

stable = summary.query(
    'Pooled_Improvement > 0.30 and Improved_Eligible_Folds == 2 and Worst_Eligible_Improvement > 0.05 and Fold3_Improvement > 0.05 and Mean_abs_move < 30 and Applied_Rows_F2 >= 10 and Applied_Rows_F3 >= 10'
).copy()

if len(stable) == 0:
    print('Agreement-gated comparable 보정이 안정성 조건을 통과하지 못했습니다. 제출 파일을 생성하지 않습니다.')
    best = summary.iloc[0].copy()
    CREATE_SUBMISSION = False
else:
    stable['OOF_Rank_Bucket'] = stable['Pooled_Improvement'].max() - stable['Pooled_Improvement'] <= 0.20
    pool = stable.loc[stable['OOF_Rank_Bucket']].copy() if stable['OOF_Rank_Bucket'].any() else stable.copy()
    best = pool.sort_values(['Mean_abs_move', 'Pooled_Improvement'], ascending=[True, False]).iloc[0].copy()
    CREATE_SUBMISSION = True
    print('선택된 24 agreement-gated comparable correction:')

display(best.to_frame('value'))
best_key = (
    best['Scope'], int(best['Prior']), int(best['TopK']), best['Gate'],
    float(best['Alpha']), int(best['Cap']), int(best['HistMinAbs'])
)
display(detail_tables[best_key])

leakage_audit = pd.Series({
    '17 baseline and comparable cache reproduced from leakage-safe notebook': True,
    'OOF comparable pools use only transactions earlier than validation months': True,
    'Agreement gate uses OOF Pred15/Pred17 only, not validation target': True,
    'Gate thresholds computed from earlier OOF folds only': True,
    'Scope/prior/top_k/gate/alpha/cap selected from Train OOF only': True,
    'No Test distribution/statistics used for selection': True,
    'Final Test comparable prediction uses full Train only after selection': True,
})
display(leakage_audit.rename('Passed'))
assert leakage_audit.all()

if CREATE_SUBMISSION:
    scope = best['Scope']
    prior = int(best['Prior'])
    top_k = int(best['TopK'])
    gate_name = best['Gate']
    alpha = float(best['Alpha'])
    cap = int(best['Cap'])
    hist_min_abs = int(best['HistMinAbs'])

    comp_test, _ = comparable_predict(train, test, scope=scope, prior=prior, top_k=top_k)
    comp_gap_test = comp_test - test_pred17
    hist_gap_test = test_pred17 - inner15['test_pred']
    agree_test = (comp_gap_test * hist_gap_test) > 0
    strong_test = np.abs(hist_gap_test) >= hist_min_abs
    bounded_test = np.abs(comp_gap_test) <= cap * 6
    gate_spec = next(g for g in GATES if g[0] == gate_name)
    _, gate_col, gate_quantile = gate_spec
    if gate_col is None:
        gate_mask_test = np.ones(len(test_frame), dtype=bool)
    else:
        threshold = oof[gate_col].quantile(gate_quantile)
        gate_mask_test = test_frame[gate_col].to_numpy() <= threshold
    mask_test = agree_test & strong_test & bounded_test & gate_mask_test
    clipped_gap_test = np.clip(comp_gap_test, -cap, cap)
    test_pred24 = test_pred17.copy()
    test_pred24[mask_test] = np.clip(test_pred17[mask_test] + alpha * clipped_gap_test[mask_test], 0, None)

    prediction_frame = pd.DataFrame({'ID': test['ID'], 'Target': test_pred24})
    submission = sample_submission[['ID']].merge(prediction_frame, on='ID', how='left', validate='one_to_one')
    assert submission['Target'].notna().all()
    assert len(submission) == len(sample_submission)
    assert sample_submission['ID'].equals(submission['ID'])
    output_path = SUBMISSION_DIR / '24_agreement_comparable_after17_submission.csv'
    submission.to_csv(output_path, index=False)
    print(f'Saved: {output_path}')
    display(submission.head())
else:
    output_path = None
    print('No submission saved for 24. Keep submitting 17_sklearn_residual_stack_submission.csv.')

result = {
    'create_submission': CREATE_SUBMISSION,
    'selected_scope': None if not CREATE_SUBMISSION else best['Scope'],
    'selected_prior': None if not CREATE_SUBMISSION else int(best['Prior']),
    'selected_top_k': None if not CREATE_SUBMISSION else int(best['TopK']),
    'selected_gate': None if not CREATE_SUBMISSION else best['Gate'],
    'selected_alpha': None if not CREATE_SUBMISSION else float(best['Alpha']),
    'selected_cap': None if not CREATE_SUBMISSION else int(best['Cap']),
    'selected_hist_min_abs': None if not CREATE_SUBMISSION else int(best['HistMinAbs']),
    'selected_oof_improvement': float(best['Pooled_Improvement']),
    'submission_path': None if output_path is None else str(output_path),
}
print(result)

Train: (1969, 11)
Train period: 202401 ~ 202512

,Fold,Train_rows,Valid_rows,04_RMSE,05_RMSE,06_RMSE,08_RMSE,09_RMSE,09_RMSLE,08_vs_06_Improvement,09_vs_08_Improvement,Local_Applied_Rows,Second_Local_Applied_Rows,Third_Local_Applied_Rows
0,Train-derived Fold 1,1201,278,"2,107.743326","2,107.743326","2,107.743326","2,107.743326","2,107.743326",0.055311,0.000000,0.000000,0,0,0
1,Train-derived Fold 2,1479,244,"2,634.763161","2,628.945780","2,621.229339","2,618.051538","2,614.984309",0.080279,3.177802,3.067229,141,103,108
2,Train-derived Fold 3,1723,246,"2,525.601387","2,522.504744","2,522.382035","2,520.144861","2,516.302312",0.071534,2.237174,3.842550,146,100,100

04 pooled RMSE: 2,420.08
05 pooled RMSE: 2,417.04
06 pooled RMSE: 2,414.33
08 pooled RMSE: 2,412.49
09 pooled RMSE: 2,410.15
Local-corrected improved folds: 2/2
Second-local improved folds: 2/2
Third-local improved folds: 2/2
08 vs 06 pooled improvement: 1.84
09 vs 08 pooled improvement: 2.34

Imputation statistics fitted on Train/fold-fit only                  True
OneHotEncoder fitted on Train/fold-fit only                          True
No independent dummy encoding on Test                                True
Fixed bins avoid validation/test distribution fitting                True
Target encoding excludes each training row target                    True
Residual model trained from time-OOF residuals only                  True
Local residual maps fitted from previous OOF residuals only          True
Second local correction selected with strict Train OOF thresholds    True
Third local correction selected with strict Train OOF thresholds     True
Validation uses strictly earlier transactions                        True
Weights, shrinkage and local corrections selected without Test       True
Test limited to transform and predict                                True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/09_residual08_cluster_correction_submission.csv

        ID        Target
0  TR_2427 36,610.203347
1  TR_0028 48,231.987381
2  TR_1461 29,100.363155
3  TR_1977 47,089.802705
4  TR_2351 47,156.525211

,Fold,Rows,09_RMSE,11_RMSE,15_RMSE,15_RMSLE,11_vs_09_Improvement,15_vs_11_Improvement,Applied_11_Rows,Applied_15_Rows,Mean_15_Move
0,1,278,"2,107.743326","2,107.743326","2,107.743326",0.055311,0.000000,0.000000,0,0,0.000000
1,2,244,"2,614.984309","2,609.888396","2,592.242694",0.079872,5.095913,17.645703,193,78,70.153712
2,3,246,"2,516.302312","2,514.519354","2,511.384324",0.071359,1.782957,3.135030,177,80,66.447489

09 pooled RMSE: 2,410.15
11 pooled RMSE: 2,407.79
15 pooled RMSE: 2,400.68
15 vs 11 pooled improvement: 7.11
Improved folds: 2/2

Market unit-price maps fitted on past Train/fold-fit only                          True
Validation market features use only transactions earlier than validation months    True
Final Test market map fitted on full Train only                                    True
Correction alpha and gate selected from Train OOF only                             True
Test limited to transform and predict                                              True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/15_market_correction_refined_submission.csv

        ID        Target
0  TR_2427 36,978.629332
1  TR_0028 48,231.987381
2  TR_1461 29,069.285497
3  TR_1977 47,636.727502
4  TR_2351 47,156.525211

,Model,Alpha,15_Pooled_RMSE,17_Pooled_RMSE,Pooled_Improvement,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold3_Improvement,Mean_abs_move
0,HistGB_leaf15,0.150000,"2,400.679317","2,399.073943",1.605374,1,-1.119264,-1.119264,70.263043
1,HistGB_leaf15,0.100000,"2,400.679317","2,399.075968",1.603349,1,-0.100697,-0.100697,46.842029
2,HistGB_leaf15,0.080000,"2,400.679317","2,399.226092",1.453226,2,0.126050,0.126050,37.473623
3,HistGB_leaf15,0.200000,"2,400.679317","2,399.605137",1.074180,1,-2.782429,-2.782429,93.684058
4,HistGB_leaf15,0.050000,"2,400.679317","2,399.611212",1.068105,2,0.272487,0.272487,23.421014
5,HistGB_leaf15,0.030000,"2,400.679317","2,399.974543",0.704775,2,0.240972,0.240972,14.052609
6,HistGB_leaf15,0.250000,"2,400.679317","2,400.669197",0.010120,1,-5.088915,-5.088915,117.105072
7,ExtraTrees_leaf5,0.000000,"2,400.679317","2,400.679317",0.000000,0,0.000000,0.000000,0.000000
8,ExtraTrees_leaf8,0.000000,"2,400.679317","2,400.679317",0.000000,0,0.000000,0.000000,0.000000
9,RandomForest_leaf8,0.000000,"2,400.679317","2,400.679317",0.000000,0,0.000000,0.000000,0.000000
10,HistGB_leaf15,0.000000,"2,400.679317","2,400.679317",0.000000,0,0.000000,0.000000,0.000000
11,RandomForest_leaf8,0.030000,"2,400.679317","2,401.215733",-0.536416,0,-0.914497,-0.914497,9.341346
12,ExtraTrees_leaf8,0.030000,"2,400.679317","2,401.347051",-0.667733,0,-1.415128,-1.415128,11.880577
13,RandomForest_leaf8,0.050000,"2,400.679317","2,401.620637",-0.941320,0,-1.594829,-1.594829,15.568909
14,ExtraTrees_leaf5,0.030000,"2,400.679317","2,401.788805",-1.109488,0,-1.950906,-1.950906,12.931418
15,ExtraTrees_leaf8,0.050000,"2,400.679317","2,401.871213",-1.191896,0,-2.453586,-2.453586,19.800962
16,HistGB_leaf15,0.300000,"2,400.679317","2,402.265414",-1.586097,1,-8.036955,-8.036955,140.526086
17,RandomForest_leaf8,0.080000,"2,400.679317","2,402.298886",-1.619569,0,-2.721214,-2.721214,24.910255
18,ExtraTrees_leaf5,0.050000,"2,400.679317","2,402.619413",-1.940096,0,-3.365311,-3.365311,21.552364
19,ExtraTrees_leaf8,0.080000,"2,400.679317","2,402.775862",-2.096545,0,-4.153599,-4.153599,31.681539

선택된 17 설정:

                                    value
Model                       HistGB_leaf15
Alpha                            0.080000
15_Pooled_RMSE               2,400.679317
17_Pooled_RMSE               2,399.226092
Pooled_Improvement               1.453226
Improved_Eligible_Folds                 2
Worst_Eligible_Improvement       0.126050
Fold3_Improvement                0.126050
Mean_abs_move                   37.473623

,Model,Alpha,Fold,Rows,15_RMSE,17_RMSE,17_vs_15_Improvement,Mean_abs_move
0,HistGB_leaf15,0.080000,1,278,"2,107.743326","2,107.743326",0.000000,0.000000
1,HistGB_leaf15,0.080000,2,244,"2,592.242694","2,588.127758",4.114936,61.369429
2,HistGB_leaf15,0.080000,3,246,"2,511.384324","2,511.258274",0.126050,51.051441

15 baseline predictions reproduced with fold-fit/past-only logic       True
Stacker fold validation uses only earlier OOF folds as fit data        True
OneHot/Imputer fit only on each stacker fit frame                      True
Residual target uses OOF Pred15, not in-sample prediction              True
Model/alpha selected by Train OOF only                                 True
Test used only for final transform/predict and submission row check    True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/17_sklearn_residual_stack_submission.csv

        ID        Target
0  TR_2427 36,937.484718
1  TR_0028 48,170.602450
2  TR_1461 29,150.967192
3  TR_1977 47,532.510021
4  TR_2351 46,969.224666

{'create_submission': True, 'selected_model': 'HistGB_leaf15', 'selected_alpha': 0.08, 'selected_oof_improvement': 1.4532255532062663, 'submission_path': '/Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/17_sklearn_residual_stack_submission.csv'}

17 pooled RMSE: 2,399.226092

,Scope,Prior,TopK,Gate,Alpha,17_Pooled_RMSE,23_Pooled_RMSE,Pooled_Improvement,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement,Mean_abs_move,Applied_Rows_F2,Applied_Rows_F3
0,gu_age,50,80,low_range_q40,0.050000,"2,399.226092","2,396.644317",2.581774,1,-3.088665,10.574024,-3.088665,38.154581,78,80
1,gu_age,50,120,low_range_q40,0.050000,"2,399.226092","2,396.644317",2.581774,1,-3.088665,10.574024,-3.088665,38.154581,78,80
2,gu_age,50,80,low_std_q40,0.050000,"2,399.226092","2,396.663919",2.562173,1,-3.632957,11.052056,-3.632957,38.434918,78,83
3,gu_age,50,120,low_std_q40,0.050000,"2,399.226092","2,396.663919",2.562173,1,-3.632957,11.052056,-3.632957,38.434918,78,83
4,gu_age,50,40,low_range_q40,0.050000,"2,399.226092","2,396.665817",2.560274,1,-2.804449,10.231621,-2.804449,37.489258,78,80
5,gu_age,50,40,low_std_q40,0.050000,"2,399.226092","2,396.702006",2.524086,1,-3.395988,10.707455,-3.395988,37.791634,78,83
6,gu_age,50,40,low_range_q40,0.080000,"2,399.226092","2,397.073881",2.152211,1,-6.679197,12.851461,-6.679197,59.982814,78,80
7,gu_age,80,80,low_range_q40,0.050000,"2,399.226092","2,397.097402",2.128690,1,-3.785839,9.933717,-3.785839,41.955223,78,80
8,gu_age,80,120,low_range_q40,0.050000,"2,399.226092","2,397.097402",2.128690,1,-3.785839,9.933717,-3.785839,41.955223,78,80
9,gu_age,50,80,low_range_q40,0.080000,"2,399.226092","2,397.099055",2.127036,1,-7.233688,13.324398,-7.233688,61.047330,78,80
10,gu_age,50,120,low_range_q40,0.080000,"2,399.226092","2,397.099055",2.127036,1,-7.233688,13.324398,-7.233688,61.047330,78,80
11,gu_age,80,80,low_std_q40,0.050000,"2,399.226092","2,397.103444",2.122647,1,-4.540949,10.658898,-4.540949,42.167285,78,83
12,gu_age,80,120,low_std_q40,0.050000,"2,399.226092","2,397.103444",2.122647,1,-4.540949,10.658898,-4.540949,42.167285,78,83
13,gu_age,80,40,low_range_q40,0.050000,"2,399.226092","2,397.109542",2.116550,1,-3.555287,9.671464,-3.555287,41.409300,78,80
14,gu_age,50,80,low_std_q40,0.080000,"2,399.226092","2,397.111312",2.114780,1,-8.179904,14.221924,-8.179904,61.495870,78,83
15,gu_age,50,120,low_std_q40,0.080000,"2,399.226092","2,397.111312",2.114780,1,-8.179904,14.221924,-8.179904,61.495870,78,83
16,gu_age,50,40,low_std_q40,0.080000,"2,399.226092","2,397.114077",2.112014,1,-7.704099,13.744351,-7.704099,60.466615,78,83
17,gu_age,80,40,low_std_q40,0.050000,"2,399.226092","2,397.129301",2.096791,1,-4.349553,10.394883,-4.349553,41.648398,78,83
18,gu_age,50,80,low_range_q40,0.030000,"2,399.226092","2,397.176354",2.049737,1,-1.279212,7.240025,-1.279212,22.892749,78,80
19,gu_age,50,120,low_range_q40,0.030000,"2,399.226092","2,397.176354",2.049737,1,-1.279212,7.240025,-1.279212,22.892749,78,80
20,gu_age,50,80,low_std_q40,0.030000,"2,399.226092","2,397.192888",2.033204,1,-1.586777,7.493595,-1.586777,23.060951,78,83
21,gu_age,50,120,low_std_q40,0.030000,"2,399.226092","2,397.192888",2.033204,1,-1.586777,7.493595,-1.586777,23.060951,78,83
22,gu_age,50,40,low_range_q40,0.030000,"2,399.226092","2,397.204143",2.021949,1,-1.133739,7.016018,-1.133739,22.493555,78,80
23,gu_age,50,40,low_std_q40,0.030000,"2,399.226092","2,397.230275",1.995817,1,-1.468875,7.268548,-1.468875,22.674981,78,83
24,gu_age,80,80,low_range_q40,0.030000,"2,399.226092","2,397.351284",1.874807,1,-1.530236,6.975005,-1.530236,25.173134,78,80
25,gu_age,80,120,low_range_q40,0.030000,"2,399.226092","2,397.351284",1.874807,1,-1.530236,6.975005,-1.530236,25.173134,78,80
26,gu_age,80,80,low_std_q40,0.030000,"2,399.226092","2,397.364137",1.861955,1,-1.964721,7.363941,-1.964721,25.300371,78,83
27,gu_age,80,120,low_std_q40,0.030000,"2,399.226092","2,397.364137",1.861955,1,-1.964721,7.363941,-1.964721,25.300371,78,83
28,gu_age,80,40,low_range_q40,0.030000,"2,399.226092","2,397.370905",1.855187,1,-1.413211,6.802794,-1.413211,24.845580,78,80
29,gu_age,80,40,low_std_q40,0.030000,"2,399.226092","2,397.391605",1.834487,1,-1.870271,7.190904,-1.870271,24.989039,78,83
30,gu_age,50,80,low_std_q50,0.050000,"2,399.226092","2,397.538239",1.687853,1,-2.241358,7.126505,-2.241358,49.673817,103,100
31,gu_age,50,120,low_std_q50,0.050000,"2,399.226092","2,397.538239",1.687853,1,-2.241358,7.126505,-2.241358,49.673817,103,100
32,gu_age,50,80,low_std_q50,0.030000,"2,399.226092","2,397.557756",1.668335,1,-0.643473,5.501599,-0.643473,29.804290,103,100
33,gu_age,50,120,low_std_q50,0.030000,"2,399.226092","2,397.557756",1.668335,1,-0.643473,5.501599,-0.643473,29.804290,103,100
34,gu_age,50,40,low_std_q50,0.050000,"2,399.226092","2,397.592120",1.633972,1,-2.006911,6.738818,-2.006911,48.872909,103,100
35,gu_age,120,80,low_range_q40,0.030000,"2,399.226092","2,397.601940",1.624152,1,-1.807900,6.514779,-1.807900,27.176267,78,80
36,gu_age,120,120,low_range_q40,0.030000,"2,399.226092","2,397.601940",1.624152,1,-1.807900,6.514779,-1.807900,27.176267,78,80
37,gu_age,50,40,low_std_q50,0.030000,"2,399.226092","2,397.607516",1.618575,1,-0.530870,5.245797,-0.530870,29.323745,103,100
38,gu_age,120,80,low_std_q40,0.030000,"2,399.226092","2,397.608003",1.618089,1,-2.343285,7.022603,-2.343285,27.321106,78,83
39,gu_age,120,120,low_std_q40,0.030000,"2,399.226092","2,397.608003",1.618089,1,-2.343285,7.022603,-2.343285,27.321106,78,83

Comparable sales 보정이 안정성 조건을 통과하지 못했습니다. 제출 파일을 생성하지 않습니다.

                                    value
Scope                              gu_age
Prior                                  50
TopK                                   80
Gate                        low_range_q40
Alpha                            0.050000
17_Pooled_RMSE               2,399.226092
23_Pooled_RMSE               2,396.644317
Pooled_Improvement               2.581774
Improved_Eligible_Folds                 1
Worst_Eligible_Improvement      -3.088665
Fold2_Improvement               10.574024
Fold3_Improvement               -3.088665
Mean_abs_move                   38.154581
Applied_Rows_F2                        78
Applied_Rows_F3                        80

,Fold,Rows,17_RMSE,23_RMSE,23_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,577.553734",10.574024,78,64.017216
2,3,246,"2,511.258274","2,514.346939",-3.088665,80,50.446528

17 baseline reproduced from leakage-safe notebook                            True
OOF comparable pools use only transactions earlier than validation months    True
Comparable group statistics fitted on fold-fit Train only                    True
Gate thresholds computed from earlier OOF folds only                         True
Scope/prior/top_k/gate/alpha selected from Train OOF only                    True
No Test distribution/statistics used for selection                           True
Final Test comparable prediction uses full Train only after selection        True
Name: Passed, dtype: bool

No submission saved for 23. Keep submitting 17_sklearn_residual_stack_submission.csv.
{'create_submission': False, 'selected_scope': None, 'selected_prior': None, 'selected_top_k': None, 'selected_gate': None, 'selected_alpha': None, 'selected_oof_improvement': 2.5817741122946245, 'submission_path': None}
17 pooled RMSE: 2,399.226092

,Scope,Prior,TopK,Gate,Alpha,Cap,HistMinAbs,17_Pooled_RMSE,24_Pooled_RMSE,Pooled_Improvement,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement,Mean_abs_move,Applied_Rows_F2,Applied_Rows_F3
0,dong,120,120,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.406692",1.819400,2,2.280004,3.079072,2.280004,12.533318,35,39
1,dong,120,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.407001",1.819090,2,2.279081,3.079072,2.279081,12.533274,35,39
2,dong,120,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.430584",1.795507,2,2.290148,2.999403,2.290148,12.365451,35,39
3,dong,120,120,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.472546",1.753546,2,1.827264,3.329908,1.827264,12.179535,34,39
4,dong,120,80,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.472855",1.753236,2,1.826341,3.329908,1.826341,12.179491,34,39
5,dong,120,40,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.501547",1.724545,2,1.822168,3.250231,1.822168,12.005489,34,39
6,dong,80,120,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.594758",1.631334,2,1.810639,2.989404,1.810639,12.018709,36,40
7,dong,80,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.595134",1.630957,2,1.809517,2.989404,1.809517,12.018652,36,40
8,gu_age,80,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.595402",1.630690,2,1.901014,1.901014,2.921301,13.088521,36,40
9,gu_age,80,120,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.595402",1.630690,2,1.901014,1.901014,2.921301,13.088521,36,40
10,gu_age,80,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.605484",1.620607,2,1.821823,1.821823,2.972203,12.891890,36,38
11,dong,80,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.680838",1.545253,2,1.808622,2.740101,1.808622,11.802012,35,40
12,dong,80,120,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.692254",1.533838,2,1.263604,3.240231,1.263604,11.626865,35,39
13,dong,80,80,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.692630",1.533462,2,1.262481,3.240231,1.262481,11.626809,35,39
14,dong,120,120,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.698819",1.527273,2,1.754635,2.740446,1.754635,6.494394,20,21
15,dong,120,80,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.698896",1.527195,2,1.754403,2.740446,1.754403,6.494594,20,21
16,gu_age,80,80,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.714934",1.511157,2,1.953691,2.498626,1.953691,12.476159,34,39
17,gu_age,80,120,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.714934",1.511157,2,1.953691,2.498626,1.953691,12.476159,34,39
18,gu_age,50,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.719649",1.506443,2,2.213251,2.213251,2.231324,12.322197,34,38
19,gu_age,80,40,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.725016",1.501075,2,2.004573,2.419416,2.004573,12.279528,34,37
20,dong,120,40,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.730773",1.495318,2,1.674296,2.725791,1.674296,6.389286,20,21
21,gu_age,50,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.733378",1.492713,2,2.147800,2.254888,2.147800,12.505091,34,40
22,gu_age,50,120,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.733378",1.492713,2,2.147800,2.254888,2.147800,12.505091,34,40
23,dong,120,120,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.747400",1.478691,2,2.155699,2.155699,2.207361,6.848177,21,21
24,dong,120,80,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.747478",1.478614,2,2.155699,2.155699,2.207130,6.848377,21,21
25,dong,120,40,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.774246",1.451846,2,2.141047,2.141047,2.142248,6.749248,21,21
26,dong,80,40,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.778330",1.447761,2,1.261587,2.990904,1.261587,11.410168,34,39
27,gu_age,120,80,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.786377",1.439715,2,2.057956,2.188101,2.057956,12.277965,35,36
28,gu_age,120,120,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.786377",1.439715,2,2.057956,2.188101,2.057956,12.277965,35,36
29,gu,120,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.808317",1.417774,2,1.528869,2.641756,1.528869,10.766442,31,36
30,gu_age,120,40,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.820007",1.406084,2,2.033326,2.114045,2.033326,12.175782,35,36
31,dong,120,120,low_range_q40,0.080000,1800,25,"2,399.226092","2,397.834908",1.391184,2,1.018091,3.064098,1.018091,9.985538,28,33
32,dong,120,80,low_range_q40,0.080000,1800,25,"2,399.226092","2,397.835217",1.390875,2,1.017168,3.064098,1.017168,9.985493,28,33
33,dong,80,120,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.846741",1.379350,2,1.251150,2.801404,1.251150,6.278384,22,21
34,dong,80,80,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.846837",1.379255,2,1.250865,2.801404,1.250865,6.278632,22,21
35,dong,120,40,low_range_q40,0.080000,1800,25,"2,399.226092","2,397.858796",1.367296,2,1.028230,2.984430,1.028230,9.817670,28,33
36,dong,80,120,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.863676",1.362416,2,1.798183,2.216643,1.798183,6.670227,23,22
37,dong,80,80,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.863771",1.362320,2,1.797898,2.216643,1.797898,6.670476,23,22
38,gu,120,40,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.864069",1.362023,2,1.983127,2.034562,1.983127,6.364367,19,21
39,gu_age,120,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.868883",1.357209,2,1.590561,1.590561,2.422714,12.671408,37,36

선택된 24 agreement-gated comparable correction:

                                  value
Scope                              dong
Prior                               120
TopK                                 40
Gate                        low_std_q50
Alpha                          0.080000
Cap                                1800
HistMinAbs                           25
17_Pooled_RMSE             2,399.226092
24_Pooled_RMSE             2,397.501547
Pooled_Improvement             1.724545
Improved_Eligible_Folds               2
Worst_Eligible_Improvement     1.822168
Fold2_Improvement              3.250231
Fold3_Improvement              1.822168
Mean_abs_move                 12.005489
Applied_Rows_F2                      34
Applied_Rows_F3                      39
OOF_Rank_Bucket                    True

,Fold,Rows,17_RMSE,24_RMSE,24_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,584.877526",3.250231,34,17.465347
2,3,246,"2,511.258274","2,509.436106",1.822168,39,18.551120

17 baseline and comparable cache reproduced from leakage-safe notebook       True
OOF comparable pools use only transactions earlier than validation months    True
Agreement gate uses OOF Pred15/Pred17 only, not validation target            True
Gate thresholds computed from earlier OOF folds only                         True
Scope/prior/top_k/gate/alpha/cap selected from Train OOF only                True
No Test distribution/statistics used for selection                           True
Final Test comparable prediction uses full Train only after selection        True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/24_agreement_comparable_after17_submission.csv

        ID        Target
0  TR_2427 36,937.484718
1  TR_0028 48,170.602450
2  TR_1461 29,294.967192
3  TR_1977 47,532.510021
4  TR_2351 46,969.224666

{'create_submission': True, 'selected_scope': 'dong', 'selected_prior': 120, 'selected_top_k': 40, 'selected_gate': 'low_std_q50', 'selected_alpha': 0.08, 'selected_cap': 1800, 'selected_hist_min_abs': 25, 'selected_oof_improvement': 1.7245450039831667, 'submission_path': '/Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/24_agreement_comparable_after17_submission.csv'}