# 33. Row-Mod Fine Ensemble

31/32에서 `Row_Mod_7` hidden residual correction이 public에도 유효하게 작동했습니다.

33번은 단일 alpha를 더 밀기보다, 31/32 주변의 여러 leakage-safe correction 후보를 만들고 Train OOF에서만 ensemble/blend를 선택합니다.

Leakage 방침:
- Public score는 실험 방향 참고용이며, 후보/가중치 선택에는 사용하지 않습니다.
- Candidate correction, gate threshold, blend weight 선택은 Train OOF에서만 수행합니다.
- Validation fold correction은 이전 OOF fold에서만 fit합니다.
- Test는 최종 선택된 후보들의 deterministic transform/predict에만 사용합니다.

In [1]:

from pathlib import Path
import json
import itertools
import numpy as np
import pandas as pd
from IPython.display import display

ROOT = Path.cwd()
if not (ROOT / 'notebooks').exists() and ROOT.name == 'notebooks':
    ROOT = ROOT.parent
NOTEBOOK_DIR = ROOT / 'notebooks'
SUBMISSION_DIR = ROOT / 'submissions'
SUBMISSION_DIR.mkdir(exist_ok=True)

pd.set_option('display.max_columns', 220)
pd.set_option('display.float_format', lambda x: f'{x:,.6f}')

def rmse(y_true, y_pred):
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    return float(np.sqrt(np.mean((y_true - y_pred) ** 2)))

def exec_notebook(path):
    path = Path(path)
    ns = {'__name__': '__notebook_exec__', '__file__': str(path)}
    notebook = json.loads(path.read_text())
    for cell in notebook['cells']:
        if cell.get('cell_type') == 'code':
            code = ''.join(cell.get('source', []))
            if code.strip():
                exec(compile(code, str(path), 'exec'), ns)
    return ns

print('Reproducing 28 best notebook...')
ns28 = exec_notebook(NOTEBOOK_DIR / '28_finer_refined_comparable.ipynb')
print('28 reproduced.')

Reproducing 28 best notebook...

Train: (1969, 11)
Train period: 202401 ~ 202512

,Fold,Train_rows,Valid_rows,04_RMSE,05_RMSE,06_RMSE,08_RMSE,09_RMSE,09_RMSLE,08_vs_06_Improvement,09_vs_08_Improvement,Local_Applied_Rows,Second_Local_Applied_Rows,Third_Local_Applied_Rows
0,Train-derived Fold 1,1201,278,"2,107.743326","2,107.743326","2,107.743326","2,107.743326","2,107.743326",0.055311,0.000000,0.000000,0,0,0
1,Train-derived Fold 2,1479,244,"2,634.763161","2,628.945780","2,621.229339","2,618.051538","2,614.984309",0.080279,3.177802,3.067229,141,103,108
2,Train-derived Fold 3,1723,246,"2,525.601387","2,522.504744","2,522.382035","2,520.144861","2,516.302312",0.071534,2.237174,3.842550,146,100,100

04 pooled RMSE: 2,420.08
05 pooled RMSE: 2,417.04
06 pooled RMSE: 2,414.33
08 pooled RMSE: 2,412.49
09 pooled RMSE: 2,410.15
Local-corrected improved folds: 2/2
Second-local improved folds: 2/2
Third-local improved folds: 2/2
08 vs 06 pooled improvement: 1.84
09 vs 08 pooled improvement: 2.34

Imputation statistics fitted on Train/fold-fit only                  True
OneHotEncoder fitted on Train/fold-fit only                          True
No independent dummy encoding on Test                                True
Fixed bins avoid validation/test distribution fitting                True
Target encoding excludes each training row target                    True
Residual model trained from time-OOF residuals only                  True
Local residual maps fitted from previous OOF residuals only          True
Second local correction selected with strict Train OOF thresholds    True
Third local correction selected with strict Train OOF thresholds     True
Validation uses strictly earlier transactions                        True
Weights, shrinkage and local corrections selected without Test       True
Test limited to transform and predict                                True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/09_residual08_cluster_correction_submission.csv

        ID        Target
0  TR_2427 36,610.203347
1  TR_0028 48,231.987381
2  TR_1461 29,100.363155
3  TR_1977 47,089.802705
4  TR_2351 47,156.525211

,Fold,Rows,09_RMSE,11_RMSE,15_RMSE,15_RMSLE,11_vs_09_Improvement,15_vs_11_Improvement,Applied_11_Rows,Applied_15_Rows,Mean_15_Move
0,1,278,"2,107.743326","2,107.743326","2,107.743326",0.055311,0.000000,0.000000,0,0,0.000000
1,2,244,"2,614.984309","2,609.888396","2,592.242694",0.079872,5.095913,17.645703,193,78,70.153712
2,3,246,"2,516.302312","2,514.519354","2,511.384324",0.071359,1.782957,3.135030,177,80,66.447489

09 pooled RMSE: 2,410.15
11 pooled RMSE: 2,407.79
15 pooled RMSE: 2,400.68
15 vs 11 pooled improvement: 7.11
Improved folds: 2/2

Market unit-price maps fitted on past Train/fold-fit only                          True
Validation market features use only transactions earlier than validation months    True
Final Test market map fitted on full Train only                                    True
Correction alpha and gate selected from Train OOF only                             True
Test limited to transform and predict                                              True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/15_market_correction_refined_submission.csv

        ID        Target
0  TR_2427 36,978.629332
1  TR_0028 48,231.987381
2  TR_1461 29,069.285497
3  TR_1977 47,636.727502
4  TR_2351 47,156.525211

,Model,Alpha,15_Pooled_RMSE,17_Pooled_RMSE,Pooled_Improvement,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold3_Improvement,Mean_abs_move
0,HistGB_leaf15,0.150000,"2,400.679317","2,399.073943",1.605374,1,-1.119264,-1.119264,70.263043
1,HistGB_leaf15,0.100000,"2,400.679317","2,399.075968",1.603349,1,-0.100697,-0.100697,46.842029
2,HistGB_leaf15,0.080000,"2,400.679317","2,399.226092",1.453226,2,0.126050,0.126050,37.473623
3,HistGB_leaf15,0.200000,"2,400.679317","2,399.605137",1.074180,1,-2.782429,-2.782429,93.684058
4,HistGB_leaf15,0.050000,"2,400.679317","2,399.611212",1.068105,2,0.272487,0.272487,23.421014
5,HistGB_leaf15,0.030000,"2,400.679317","2,399.974543",0.704775,2,0.240972,0.240972,14.052609
6,HistGB_leaf15,0.250000,"2,400.679317","2,400.669197",0.010120,1,-5.088915,-5.088915,117.105072
7,ExtraTrees_leaf5,0.000000,"2,400.679317","2,400.679317",0.000000,0,0.000000,0.000000,0.000000
8,ExtraTrees_leaf8,0.000000,"2,400.679317","2,400.679317",0.000000,0,0.000000,0.000000,0.000000
9,RandomForest_leaf8,0.000000,"2,400.679317","2,400.679317",0.000000,0,0.000000,0.000000,0.000000
10,HistGB_leaf15,0.000000,"2,400.679317","2,400.679317",0.000000,0,0.000000,0.000000,0.000000
11,RandomForest_leaf8,0.030000,"2,400.679317","2,401.215733",-0.536416,0,-0.914497,-0.914497,9.341346
12,ExtraTrees_leaf8,0.030000,"2,400.679317","2,401.347051",-0.667733,0,-1.415128,-1.415128,11.880577
13,RandomForest_leaf8,0.050000,"2,400.679317","2,401.620637",-0.941320,0,-1.594829,-1.594829,15.568909
14,ExtraTrees_leaf5,0.030000,"2,400.679317","2,401.788805",-1.109488,0,-1.950906,-1.950906,12.931418
15,ExtraTrees_leaf8,0.050000,"2,400.679317","2,401.871213",-1.191896,0,-2.453586,-2.453586,19.800962
16,HistGB_leaf15,0.300000,"2,400.679317","2,402.265414",-1.586097,1,-8.036955,-8.036955,140.526086
17,RandomForest_leaf8,0.080000,"2,400.679317","2,402.298886",-1.619569,0,-2.721214,-2.721214,24.910255
18,ExtraTrees_leaf5,0.050000,"2,400.679317","2,402.619413",-1.940096,0,-3.365311,-3.365311,21.552364
19,ExtraTrees_leaf8,0.080000,"2,400.679317","2,402.775862",-2.096545,0,-4.153599,-4.153599,31.681539

선택된 17 설정:

                                    value
Model                       HistGB_leaf15
Alpha                            0.080000
15_Pooled_RMSE               2,400.679317
17_Pooled_RMSE               2,399.226092
Pooled_Improvement               1.453226
Improved_Eligible_Folds                 2
Worst_Eligible_Improvement       0.126050
Fold3_Improvement                0.126050
Mean_abs_move                   37.473623

,Model,Alpha,Fold,Rows,15_RMSE,17_RMSE,17_vs_15_Improvement,Mean_abs_move
0,HistGB_leaf15,0.080000,1,278,"2,107.743326","2,107.743326",0.000000,0.000000
1,HistGB_leaf15,0.080000,2,244,"2,592.242694","2,588.127758",4.114936,61.369429
2,HistGB_leaf15,0.080000,3,246,"2,511.384324","2,511.258274",0.126050,51.051441

15 baseline predictions reproduced with fold-fit/past-only logic       True
Stacker fold validation uses only earlier OOF folds as fit data        True
OneHot/Imputer fit only on each stacker fit frame                      True
Residual target uses OOF Pred15, not in-sample prediction              True
Model/alpha selected by Train OOF only                                 True
Test used only for final transform/predict and submission row check    True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/17_sklearn_residual_stack_submission.csv

        ID        Target
0  TR_2427 36,937.484718
1  TR_0028 48,170.602450
2  TR_1461 29,150.967192
3  TR_1977 47,532.510021
4  TR_2351 46,969.224666

{'create_submission': True, 'selected_model': 'HistGB_leaf15', 'selected_alpha': 0.08, 'selected_oof_improvement': 1.4532255532062663, 'submission_path': '/Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/17_sklearn_residual_stack_submission.csv'}

17 pooled RMSE: 2,399.226092

,Scope,Prior,TopK,Gate,Alpha,17_Pooled_RMSE,23_Pooled_RMSE,Pooled_Improvement,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement,Mean_abs_move,Applied_Rows_F2,Applied_Rows_F3
0,gu_age,50,80,low_range_q40,0.050000,"2,399.226092","2,396.644317",2.581774,1,-3.088665,10.574024,-3.088665,38.154581,78,80
1,gu_age,50,120,low_range_q40,0.050000,"2,399.226092","2,396.644317",2.581774,1,-3.088665,10.574024,-3.088665,38.154581,78,80
2,gu_age,50,80,low_std_q40,0.050000,"2,399.226092","2,396.663919",2.562173,1,-3.632957,11.052056,-3.632957,38.434918,78,83
3,gu_age,50,120,low_std_q40,0.050000,"2,399.226092","2,396.663919",2.562173,1,-3.632957,11.052056,-3.632957,38.434918,78,83
4,gu_age,50,40,low_range_q40,0.050000,"2,399.226092","2,396.665817",2.560274,1,-2.804449,10.231621,-2.804449,37.489258,78,80
5,gu_age,50,40,low_std_q40,0.050000,"2,399.226092","2,396.702006",2.524086,1,-3.395988,10.707455,-3.395988,37.791634,78,83
6,gu_age,50,40,low_range_q40,0.080000,"2,399.226092","2,397.073881",2.152211,1,-6.679197,12.851461,-6.679197,59.982814,78,80
7,gu_age,80,80,low_range_q40,0.050000,"2,399.226092","2,397.097402",2.128690,1,-3.785839,9.933717,-3.785839,41.955223,78,80
8,gu_age,80,120,low_range_q40,0.050000,"2,399.226092","2,397.097402",2.128690,1,-3.785839,9.933717,-3.785839,41.955223,78,80
9,gu_age,50,80,low_range_q40,0.080000,"2,399.226092","2,397.099055",2.127036,1,-7.233688,13.324398,-7.233688,61.047330,78,80
10,gu_age,50,120,low_range_q40,0.080000,"2,399.226092","2,397.099055",2.127036,1,-7.233688,13.324398,-7.233688,61.047330,78,80
11,gu_age,80,80,low_std_q40,0.050000,"2,399.226092","2,397.103444",2.122647,1,-4.540949,10.658898,-4.540949,42.167285,78,83
12,gu_age,80,120,low_std_q40,0.050000,"2,399.226092","2,397.103444",2.122647,1,-4.540949,10.658898,-4.540949,42.167285,78,83
13,gu_age,80,40,low_range_q40,0.050000,"2,399.226092","2,397.109542",2.116550,1,-3.555287,9.671464,-3.555287,41.409300,78,80
14,gu_age,50,80,low_std_q40,0.080000,"2,399.226092","2,397.111312",2.114780,1,-8.179904,14.221924,-8.179904,61.495870,78,83
15,gu_age,50,120,low_std_q40,0.080000,"2,399.226092","2,397.111312",2.114780,1,-8.179904,14.221924,-8.179904,61.495870,78,83
16,gu_age,50,40,low_std_q40,0.080000,"2,399.226092","2,397.114077",2.112014,1,-7.704099,13.744351,-7.704099,60.466615,78,83
17,gu_age,80,40,low_std_q40,0.050000,"2,399.226092","2,397.129301",2.096791,1,-4.349553,10.394883,-4.349553,41.648398,78,83
18,gu_age,50,80,low_range_q40,0.030000,"2,399.226092","2,397.176354",2.049737,1,-1.279212,7.240025,-1.279212,22.892749,78,80
19,gu_age,50,120,low_range_q40,0.030000,"2,399.226092","2,397.176354",2.049737,1,-1.279212,7.240025,-1.279212,22.892749,78,80
20,gu_age,50,80,low_std_q40,0.030000,"2,399.226092","2,397.192888",2.033204,1,-1.586777,7.493595,-1.586777,23.060951,78,83
21,gu_age,50,120,low_std_q40,0.030000,"2,399.226092","2,397.192888",2.033204,1,-1.586777,7.493595,-1.586777,23.060951,78,83
22,gu_age,50,40,low_range_q40,0.030000,"2,399.226092","2,397.204143",2.021949,1,-1.133739,7.016018,-1.133739,22.493555,78,80
23,gu_age,50,40,low_std_q40,0.030000,"2,399.226092","2,397.230275",1.995817,1,-1.468875,7.268548,-1.468875,22.674981,78,83
24,gu_age,80,80,low_range_q40,0.030000,"2,399.226092","2,397.351284",1.874807,1,-1.530236,6.975005,-1.530236,25.173134,78,80
25,gu_age,80,120,low_range_q40,0.030000,"2,399.226092","2,397.351284",1.874807,1,-1.530236,6.975005,-1.530236,25.173134,78,80
26,gu_age,80,80,low_std_q40,0.030000,"2,399.226092","2,397.364137",1.861955,1,-1.964721,7.363941,-1.964721,25.300371,78,83
27,gu_age,80,120,low_std_q40,0.030000,"2,399.226092","2,397.364137",1.861955,1,-1.964721,7.363941,-1.964721,25.300371,78,83
28,gu_age,80,40,low_range_q40,0.030000,"2,399.226092","2,397.370905",1.855187,1,-1.413211,6.802794,-1.413211,24.845580,78,80
29,gu_age,80,40,low_std_q40,0.030000,"2,399.226092","2,397.391605",1.834487,1,-1.870271,7.190904,-1.870271,24.989039,78,83
30,gu_age,50,80,low_std_q50,0.050000,"2,399.226092","2,397.538239",1.687853,1,-2.241358,7.126505,-2.241358,49.673817,103,100
31,gu_age,50,120,low_std_q50,0.050000,"2,399.226092","2,397.538239",1.687853,1,-2.241358,7.126505,-2.241358,49.673817,103,100
32,gu_age,50,80,low_std_q50,0.030000,"2,399.226092","2,397.557756",1.668335,1,-0.643473,5.501599,-0.643473,29.804290,103,100
33,gu_age,50,120,low_std_q50,0.030000,"2,399.226092","2,397.557756",1.668335,1,-0.643473,5.501599,-0.643473,29.804290,103,100
34,gu_age,50,40,low_std_q50,0.050000,"2,399.226092","2,397.592120",1.633972,1,-2.006911,6.738818,-2.006911,48.872909,103,100
35,gu_age,120,80,low_range_q40,0.030000,"2,399.226092","2,397.601940",1.624152,1,-1.807900,6.514779,-1.807900,27.176267,78,80
36,gu_age,120,120,low_range_q40,0.030000,"2,399.226092","2,397.601940",1.624152,1,-1.807900,6.514779,-1.807900,27.176267,78,80
37,gu_age,50,40,low_std_q50,0.030000,"2,399.226092","2,397.607516",1.618575,1,-0.530870,5.245797,-0.530870,29.323745,103,100
38,gu_age,120,80,low_std_q40,0.030000,"2,399.226092","2,397.608003",1.618089,1,-2.343285,7.022603,-2.343285,27.321106,78,83
39,gu_age,120,120,low_std_q40,0.030000,"2,399.226092","2,397.608003",1.618089,1,-2.343285,7.022603,-2.343285,27.321106,78,83

Comparable sales 보정이 안정성 조건을 통과하지 못했습니다. 제출 파일을 생성하지 않습니다.

                                    value
Scope                              gu_age
Prior                                  50
TopK                                   80
Gate                        low_range_q40
Alpha                            0.050000
17_Pooled_RMSE               2,399.226092
23_Pooled_RMSE               2,396.644317
Pooled_Improvement               2.581774
Improved_Eligible_Folds                 1
Worst_Eligible_Improvement      -3.088665
Fold2_Improvement               10.574024
Fold3_Improvement               -3.088665
Mean_abs_move                   38.154581
Applied_Rows_F2                        78
Applied_Rows_F3                        80

,Fold,Rows,17_RMSE,23_RMSE,23_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,577.553734",10.574024,78,64.017216
2,3,246,"2,511.258274","2,514.346939",-3.088665,80,50.446528

17 baseline reproduced from leakage-safe notebook                            True
OOF comparable pools use only transactions earlier than validation months    True
Comparable group statistics fitted on fold-fit Train only                    True
Gate thresholds computed from earlier OOF folds only                         True
Scope/prior/top_k/gate/alpha selected from Train OOF only                    True
No Test distribution/statistics used for selection                           True
Final Test comparable prediction uses full Train only after selection        True
Name: Passed, dtype: bool

No submission saved for 23. Keep submitting 17_sklearn_residual_stack_submission.csv.
{'create_submission': False, 'selected_scope': None, 'selected_prior': None, 'selected_top_k': None, 'selected_gate': None, 'selected_alpha': None, 'selected_oof_improvement': 2.5817741122946245, 'submission_path': None}
17 pooled RMSE: 2,399.226092

,Scope,Prior,TopK,Gate,Alpha,Cap,HistMinAbs,17_Pooled_RMSE,24_Pooled_RMSE,Pooled_Improvement,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement,Mean_abs_move,Applied_Rows_F2,Applied_Rows_F3
0,dong,120,120,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.406692",1.819400,2,2.280004,3.079072,2.280004,12.533318,35,39
1,dong,120,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.407001",1.819090,2,2.279081,3.079072,2.279081,12.533274,35,39
2,dong,120,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.430584",1.795507,2,2.290148,2.999403,2.290148,12.365451,35,39
3,dong,120,120,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.472546",1.753546,2,1.827264,3.329908,1.827264,12.179535,34,39
4,dong,120,80,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.472855",1.753236,2,1.826341,3.329908,1.826341,12.179491,34,39
5,dong,120,40,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.501547",1.724545,2,1.822168,3.250231,1.822168,12.005489,34,39
6,dong,80,120,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.594758",1.631334,2,1.810639,2.989404,1.810639,12.018709,36,40
7,dong,80,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.595134",1.630957,2,1.809517,2.989404,1.809517,12.018652,36,40
8,gu_age,80,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.595402",1.630690,2,1.901014,1.901014,2.921301,13.088521,36,40
9,gu_age,80,120,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.595402",1.630690,2,1.901014,1.901014,2.921301,13.088521,36,40
10,gu_age,80,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.605484",1.620607,2,1.821823,1.821823,2.972203,12.891890,36,38
11,dong,80,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.680838",1.545253,2,1.808622,2.740101,1.808622,11.802012,35,40
12,dong,80,120,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.692254",1.533838,2,1.263604,3.240231,1.263604,11.626865,35,39
13,dong,80,80,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.692630",1.533462,2,1.262481,3.240231,1.262481,11.626809,35,39
14,dong,120,120,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.698819",1.527273,2,1.754635,2.740446,1.754635,6.494394,20,21
15,dong,120,80,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.698896",1.527195,2,1.754403,2.740446,1.754403,6.494594,20,21
16,gu_age,80,80,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.714934",1.511157,2,1.953691,2.498626,1.953691,12.476159,34,39
17,gu_age,80,120,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.714934",1.511157,2,1.953691,2.498626,1.953691,12.476159,34,39
18,gu_age,50,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.719649",1.506443,2,2.213251,2.213251,2.231324,12.322197,34,38
19,gu_age,80,40,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.725016",1.501075,2,2.004573,2.419416,2.004573,12.279528,34,37
20,dong,120,40,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.730773",1.495318,2,1.674296,2.725791,1.674296,6.389286,20,21
21,gu_age,50,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.733378",1.492713,2,2.147800,2.254888,2.147800,12.505091,34,40
22,gu_age,50,120,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.733378",1.492713,2,2.147800,2.254888,2.147800,12.505091,34,40
23,dong,120,120,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.747400",1.478691,2,2.155699,2.155699,2.207361,6.848177,21,21
24,dong,120,80,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.747478",1.478614,2,2.155699,2.155699,2.207130,6.848377,21,21
25,dong,120,40,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.774246",1.451846,2,2.141047,2.141047,2.142248,6.749248,21,21
26,dong,80,40,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.778330",1.447761,2,1.261587,2.990904,1.261587,11.410168,34,39
27,gu_age,120,80,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.786377",1.439715,2,2.057956,2.188101,2.057956,12.277965,35,36
28,gu_age,120,120,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.786377",1.439715,2,2.057956,2.188101,2.057956,12.277965,35,36
29,gu,120,40,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.808317",1.417774,2,1.528869,2.641756,1.528869,10.766442,31,36
30,gu_age,120,40,low_std_q50,0.080000,1800,25,"2,399.226092","2,397.820007",1.406084,2,2.033326,2.114045,2.033326,12.175782,35,36
31,dong,120,120,low_range_q40,0.080000,1800,25,"2,399.226092","2,397.834908",1.391184,2,1.018091,3.064098,1.018091,9.985538,28,33
32,dong,120,80,low_range_q40,0.080000,1800,25,"2,399.226092","2,397.835217",1.390875,2,1.017168,3.064098,1.017168,9.985493,28,33
33,dong,80,120,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.846741",1.379350,2,1.251150,2.801404,1.251150,6.278384,22,21
34,dong,80,80,low_std_q50,0.080000,1800,50,"2,399.226092","2,397.846837",1.379255,2,1.250865,2.801404,1.250865,6.278632,22,21
35,dong,120,40,low_range_q40,0.080000,1800,25,"2,399.226092","2,397.858796",1.367296,2,1.028230,2.984430,1.028230,9.817670,28,33
36,dong,80,120,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.863676",1.362416,2,1.798183,2.216643,1.798183,6.670227,23,22
37,dong,80,80,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.863771",1.362320,2,1.797898,2.216643,1.797898,6.670476,23,22
38,gu,120,40,low_range_q50,0.080000,1800,50,"2,399.226092","2,397.864069",1.362023,2,1.983127,2.034562,1.983127,6.364367,19,21
39,gu_age,120,80,low_range_q50,0.080000,1800,25,"2,399.226092","2,397.868883",1.357209,2,1.590561,1.590561,2.422714,12.671408,37,36

선택된 24 agreement-gated comparable correction:

                                  value
Scope                              dong
Prior                               120
TopK                                 40
Gate                        low_std_q50
Alpha                          0.080000
Cap                                1800
HistMinAbs                           25
17_Pooled_RMSE             2,399.226092
24_Pooled_RMSE             2,397.501547
Pooled_Improvement             1.724545
Improved_Eligible_Folds               2
Worst_Eligible_Improvement     1.822168
Fold2_Improvement              3.250231
Fold3_Improvement              1.822168
Mean_abs_move                 12.005489
Applied_Rows_F2                      34
Applied_Rows_F3                      39
OOF_Rank_Bucket                    True

,Fold,Rows,17_RMSE,24_RMSE,24_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,584.877526",3.250231,34,17.465347
2,3,246,"2,511.258274","2,509.436106",1.822168,39,18.551120

17 baseline and comparable cache reproduced from leakage-safe notebook       True
OOF comparable pools use only transactions earlier than validation months    True
Agreement gate uses OOF Pred15/Pred17 only, not validation target            True
Gate thresholds computed from earlier OOF folds only                         True
Scope/prior/top_k/gate/alpha/cap selected from Train OOF only                True
No Test distribution/statistics used for selection                           True
Final Test comparable prediction uses full Train only after selection        True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/24_agreement_comparable_after17_submission.csv

        ID        Target
0  TR_2427 36,937.484718
1  TR_0028 48,170.602450
2  TR_1461 29,294.967192
3  TR_1977 47,532.510021
4  TR_2351 46,969.224666

{'create_submission': True, 'selected_scope': 'dong', 'selected_prior': 120, 'selected_top_k': 40, 'selected_gate': 'low_std_q50', 'selected_alpha': 0.08, 'selected_cap': 1800, 'selected_hist_min_abs': 25, 'selected_oof_improvement': 1.7245450039831667, 'submission_path': '/Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/24_agreement_comparable_after17_submission.csv'}

,Scope,Prior,TopK,Gate,Alpha,Cap,HistMinAbs,17_Pooled_RMSE,25_Pooled_RMSE,Pooled_Improvement,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement,Mean_abs_move,Applied_Rows_F2,Applied_Rows_F3,Is_24_Config
0,dong,120,60,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.571154",2.654938,2,3.886418,3.946368,3.886418,20.410855,36,41,False
1,dong,150,60,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.575452",2.650640,2,3.761903,4.055632,3.761903,20.831767,36,41,False
2,dong,120,40,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.606590",2.619502,2,3.793841,3.793841,3.936603,20.192729,36,41,False
3,dong,150,40,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.612108",2.613983,2,3.774926,3.935887,3.774926,20.623612,36,39,False
4,dong,120,30,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.622488",2.603604,2,3.700678,3.700678,3.984407,20.118370,36,41,False
5,dong,150,30,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.625932",2.600160,2,3.809192,3.862015,3.809192,20.568314,36,39,False
6,dong,100,60,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.637971",2.588120,2,3.799573,3.836281,3.799573,19.965096,35,41,False
7,gu_age,150,60,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.667928",2.558164,2,3.095275,3.095275,4.467884,21.303533,38,37,False
8,gu_age,150,40,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.703195",2.522897,2,3.015936,3.015936,4.443770,21.217598,38,37,False
9,dong,100,40,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.710524",2.515567,2,3.566572,3.566572,3.858802,20.046762,36,41,False
10,dong,100,30,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.729757",2.496335,2,3.459039,3.459039,3.911353,19.955136,37,41,False
11,gu_age,100,60,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.774210",2.451882,2,3.227093,3.227093,4.015862,21.235077,38,39,False
12,gu_age,120,60,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.806075",2.420016,2,3.230081,3.230081,3.917709,21.448061,38,39,False
13,gu_age,100,40,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.843626",2.382466,2,3.089994,3.089994,3.948895,21.057473,38,37,False
14,gu_age,120,40,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.856475",2.369617,2,3.120020,3.120020,3.879844,21.323022,38,39,False
15,gu_age,150,60,low_std_q50,0.100000,2400,25,"2,399.226092","2,396.859429",2.366663,2,2.845113,4.123686,2.845113,20.194660,36,36,False
16,gu_age,150,40,low_std_q50,0.100000,2400,25,"2,399.226092","2,396.894693",2.331399,2,2.821015,4.044316,2.821015,20.108724,36,36,False
17,dong,150,60,low_std_q50,0.100000,2400,25,"2,399.226092","2,396.913450",2.312642,2,1.697971,5.089115,1.697971,19.608210,34,40,False
18,dong,120,60,low_std_q50,0.100000,2400,25,"2,399.226092","2,396.940125",2.285966,2,1.730026,4.979807,1.730026,19.149459,34,40,False
19,dong,150,40,low_std_q50,0.100000,2400,25,"2,399.226092","2,396.953540",2.272552,2,1.700731,4.969322,1.700731,19.395829,34,38,False
20,dong,150,60,low_range_q50,0.080000,2400,25,"2,399.226092","2,396.958226",2.267865,2,3.234298,3.454453,3.234298,16.665414,36,41,False
21,dong,150,30,low_std_q50,0.100000,2400,25,"2,399.226092","2,396.959396",2.266695,2,1.758719,4.895420,1.758719,19.350330,34,38,False
22,dong,120,60,low_range_q50,0.080000,2400,25,"2,399.226092","2,396.960228",2.265864,2,3.329184,3.355788,3.329184,16.328684,36,41,False
23,dong,120,40,low_std_q50,0.100000,2400,25,"2,399.226092","2,396.979595",2.246496,2,1.768122,4.827219,1.768122,18.926436,34,40,False
24,gu_age,100,30,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.985621",2.240471,2,2.855575,2.855575,3.764851,20.901910,37,38,False
25,dong,120,30,low_std_q50,0.100000,2400,25,"2,399.226092","2,396.986136",2.239956,2,1.843784,4.734019,1.843784,18.863432,34,40,False
26,dong,150,40,low_range_q50,0.080000,2400,25,"2,399.226092","2,396.988955",2.237137,2,3.242744,3.356497,3.242744,16.498890,36,39,False
27,dong,120,40,low_range_q50,0.080000,2400,25,"2,399.226092","2,396.990097",2.235994,2,3.231992,3.231992,3.366613,16.154183,36,41,False
28,gu_age,120,30,low_range_q50,0.100000,2400,25,"2,399.226092","2,396.990924",2.235167,2,2.899927,2.899927,3.703668,21.182166,38,37,False
29,gu_age,100,60,low_std_q50,0.100000,2400,25,"2,399.226092","2,396.992522",2.233570,2,2.313418,4.255532,2.313418,20.090764,36,38,False
30,dong,150,30,low_range_q50,0.080000,2400,25,"2,399.226092","2,397.000468",2.225623,2,3.270217,3.296016,3.270217,16.454651,36,39,False
31,dong,120,30,low_range_q50,0.080000,2400,25,"2,399.226092","2,397.003288",2.222804,2,3.156650,3.156650,3.404281,16.094696,36,41,False
32,dong,150,60,low_range_q50,0.100000,1800,25,"2,399.226092","2,397.006424",2.219667,2,2.802042,3.736692,2.802042,15.759377,35,39,False
33,gu_age,120,60,low_std_q50,0.100000,2400,25,"2,399.226092","2,397.011642",2.214449,2,2.253280,4.258574,2.253280,20.320942,36,38,False
34,dong,100,60,low_range_q50,0.080000,2400,25,"2,399.226092","2,397.017408",2.208684,2,3.255888,3.260589,3.255888,15.972077,35,41,False
35,gu_age,150,60,low_range_q50,0.080000,2400,25,"2,399.226092","2,397.024862",2.201229,2,2.700633,2.700633,3.806193,17.042827,38,37,False
36,gu_age,150,30,low_range_q50,0.100000,2400,25,"2,399.226092","2,397.026315",2.199777,2,2.890619,2.890619,3.607572,21.483441,38,38,False
37,dong,120,60,low_range_q50,0.100000,2400,50,"2,399.226092","2,397.031070",2.195022,2,2.489456,2.489456,4.003657,11.624752,22,23,False
38,dong,150,40,low_range_q50,0.100000,1800,25,"2,399.226092","2,397.031307",2.194785,2,2.805623,3.660548,2.805623,15.590510,35,37,False
39,dong,100,60,low_std_q50,0.100000,2400,25,"2,399.226092","2,397.032561",2.193531,2,1.566835,4.869676,1.566835,18.672774,33,40,False

Reproduced 24 config:

                                  value
Scope                              dong
Prior                               120
TopK                                 40
Gate                        low_std_q50
Alpha                          0.080000
Cap                                1800
HistMinAbs                           25
17_Pooled_RMSE             2,399.226092
25_Pooled_RMSE             2,397.501547
Pooled_Improvement             1.724545
Improved_Eligible_Folds               2
Worst_Eligible_Improvement     1.822168
Fold2_Improvement              3.250231
Fold3_Improvement              1.822168
Mean_abs_move                 12.005489
Applied_Rows_F2                      34
Applied_Rows_F3                      39
Is_24_Config                       True

,Fold,Rows,17_RMSE,25_RMSE,25_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,584.877526",3.250231,34,17.465347
2,3,246,"2,511.258274","2,509.436106",1.822168,39,18.551120

선택된 25 refined agreement comparable correction:

                                    value
Scope                                dong
Prior                                 100
TopK                                   30
Gate                        low_range_q50
Alpha                            0.100000
Cap                                  2400
HistMinAbs                             25
17_Pooled_RMSE               2,399.226092
25_Pooled_RMSE               2,396.729757
Pooled_Improvement               2.496335
Improved_Eligible_Folds                 2
Worst_Eligible_Improvement       3.459039
Fold2_Improvement                3.459039
Fold3_Improvement                3.911353
Mean_abs_move                   19.955136
Applied_Rows_F2                        37
Applied_Rows_F3                        41
Is_24_Config                        False
Distance_From_24                 1.800000
OOF_Rank_Bucket                      True

,Fold,Rows,17_RMSE,25_RMSE,25_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,584.668719",3.459039,37,28.931292
2,3,246,"2,511.258274","2,507.346921",3.911353,41,30.934115

,Weight25,Pooled_Improvement,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement
4,1.000000,2.496335,3.459039,3.459039,3.911353
3,0.900000,2.439326,3.469725,3.469725,3.730304
2,0.800000,2.377833,3.473397,3.473397,3.543057
1,0.700000,2.311858,3.349615,3.470053,3.349615
0,0.500000,2.166461,2.944150,3.442320,2.944150

24 baseline reproduced from leakage-safe notebook                            True
OOF comparable pools use only transactions earlier than validation months    True
Agreement gate uses OOF Pred15/Pred17 only, not validation target            True
Gate thresholds computed from earlier OOF folds only                         True
All refinement choices selected from Train OOF only                          True
No Test distribution/statistics used for selection                           True
Final Test comparable prediction uses full Train only after selection        True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/25_refined_agreement_comparable_submission.csv

        ID        Target
0  TR_2427 36,937.484718
1  TR_0028 48,170.602450
2  TR_1461 29,300.944712
3  TR_1977 47,532.510021
4  TR_2351 46,969.224666

{'create_submission': True, 'selected_scope': 'dong', 'selected_prior': 100, 'selected_top_k': 30, 'selected_gate': 'low_range_q50', 'selected_alpha': 0.1, 'selected_cap': 2400, 'selected_hist_min_abs': 25, 'selected_oof_improvement': 2.49633462772681, 'submission_path': '/Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/25_refined_agreement_comparable_submission.csv'}

,Scope,Prior,TopK,Gate,Alpha,Cap,HistMinAbs,17_Pooled_RMSE,27_Pooled_RMSE,Pooled_Improvement,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement,Mean_abs_move,Applied_Rows_F2,Applied_Rows_F3,Is_25_Config
0,dong,120,40,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.224993",3.001099,2,4.315132,4.315132,4.542428,26.507046,37,41,False
1,dong,120,30,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.237100",2.988991,2,4.202343,4.202343,4.621611,26.399367,37,41,False
2,dong,120,25,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.242025",2.984066,2,4.187252,4.187252,4.622341,26.275542,37,41,False
3,dong,120,35,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.244799",2.981293,2,4.263349,4.263349,4.536261,26.446222,37,41,False
4,dong,110,40,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.251180",2.974912,2,4.254791,4.254791,4.525967,26.245146,37,41,False
5,dong,110,25,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.258678",2.967414,2,4.125386,4.125386,4.635900,25.998865,37,41,False
6,dong,110,30,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.262942",2.963150,2,4.139971,4.139971,4.608260,26.122121,37,41,False
7,dong,110,35,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.269220",2.956872,2,4.199817,4.199817,4.528335,26.184453,37,41,False
8,dong,120,40,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.291910",2.934182,2,4.218864,4.218864,4.441147,25.354566,37,41,False
9,dong,120,20,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.293921",2.932171,2,4.106554,4.106554,4.549974,26.199241,37,41,False
10,dong,100,40,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.294713",2.931379,2,4.215977,4.215977,4.435735,25.917171,36,41,False
11,dong,100,25,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.300798",2.925294,2,4.070501,4.070501,4.566312,25.647441,37,41,False
12,dong,120,30,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.303764",2.922328,2,4.110532,4.110532,4.516530,25.251568,37,41,False
13,dong,120,40,low_range_q50,0.115000,2600,25,"2,399.226092","2,396.305473",2.920619,2,4.188977,4.188977,4.431228,25.078090,37,41,False
14,dong,120,25,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.308931",2.917160,2,4.095679,4.095679,4.516295,25.133127,37,41,False
15,dong,110,20,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.310520",2.915572,2,4.040151,4.040151,4.568330,25.921319,37,41,False
16,dong,120,35,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.310921",2.915170,2,4.169401,4.169401,4.434981,25.296386,37,41,False
17,dong,100,30,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.314860",2.911231,2,4.069318,4.069318,4.525553,25.777412,37,41,False
18,dong,110,40,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.317729",2.908363,2,4.160009,4.160009,4.424268,25.104053,37,41,False
19,dong,120,35,low_range_q50,0.115000,2600,25,"2,399.226092","2,396.324753",2.901339,2,4.137196,4.137196,4.426629,25.016710,37,41,False
20,dong,110,25,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.325681",2.900410,2,4.035163,4.035163,4.528181,24.868480,37,41,False
21,dong,120,30,low_range_q50,0.115000,2600,25,"2,399.226092","2,396.326187",2.899904,2,4.076261,4.076261,4.484650,24.981709,37,41,False
22,dong,110,40,low_range_q50,0.115000,2600,25,"2,399.226092","2,396.326440",2.899652,2,4.128638,4.128638,4.430345,24.840125,37,41,False
23,dong,100,35,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.327091",2.899001,2,4.127072,4.127072,4.430004,25.852219,36,41,False
24,dong,110,30,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.329313",2.896779,2,4.049598,4.049598,4.502583,24.986376,37,41,False
25,dong,110,35,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.335028",2.891064,2,4.107509,4.107509,4.426316,25.045998,37,41,False
26,dong,100,20,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.344893",2.881198,2,3.999541,3.999541,4.507266,25.564231,37,41,False
27,dong,120,25,low_range_q50,0.115000,2600,25,"2,399.226092","2,396.345267",2.880825,2,4.051409,4.051409,4.453119,24.900679,37,41,False
28,dong,110,30,low_range_q50,0.115000,2600,25,"2,399.226092","2,396.347202",2.878889,2,4.008912,4.008912,4.490794,24.738093,37,41,False
29,dong,110,35,low_range_q50,0.115000,2600,25,"2,399.226092","2,396.349578",2.876513,2,4.073667,4.073667,4.417495,24.770789,37,41,False
30,dong,110,25,low_range_q50,0.115000,2600,25,"2,399.226092","2,396.350977",2.875115,2,3.985049,3.985049,4.503929,24.642821,37,41,False
31,dong,90,40,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.351955",2.874137,2,4.176769,4.176769,4.304992,25.515499,36,41,False
32,dong,120,20,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.358816",2.867276,2,4.017767,4.017767,4.447080,25.060144,37,41,False
33,dong,90,25,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.358874",2.867217,2,4.020078,4.020078,4.444543,25.212217,36,41,False
34,dong,100,40,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.360253",2.865838,2,4.121612,4.121612,4.336618,24.790338,36,41,False
35,dong,120,40,low_range_q50,0.105000,2800,25,"2,399.226092","2,396.364611",2.861481,2,4.114281,4.114281,4.331109,24.202086,37,41,False
36,dong,120,40,low_range_q50,0.115000,2400,25,"2,399.226092","2,396.365074",2.861018,2,4.150522,4.150522,4.292676,23.221638,36,41,False
37,dong,100,25,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.366896",2.859195,2,3.981244,3.981244,4.460308,24.532335,37,41,False
38,dong,90,30,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.373649",2.852442,2,4.019846,4.019846,4.400687,25.353544,36,41,False
39,dong,110,20,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.375532",2.850560,2,3.952880,3.952880,4.463538,24.794305,37,41,False
40,dong,120,30,low_range_q50,0.105000,2800,25,"2,399.226092","2,396.376187",2.849905,2,4.010448,4.010448,4.402723,24.103770,37,41,False
41,dong,120,40,low_range_q50,0.110000,2600,25,"2,399.226092","2,396.376256",2.849836,2,4.087364,4.087364,4.323876,23.987738,37,41,False
42,dong,100,30,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.379871",2.846221,2,3.980721,3.980721,4.422122,24.656655,37,41,False
43,dong,120,25,low_range_q50,0.105000,2800,25,"2,399.226092","2,396.381554",2.844537,2,3.995870,3.995870,4.401608,23.990713,37,41,False
44,dong,120,35,low_range_q50,0.105000,2800,25,"2,399.226092","2,396.382822",2.843270,2,4.067133,4.067133,4.324966,24.146551,37,41,False
45,dong,120,30,low_range_q50,0.115000,2400,25,"2,399.226092","2,396.382848",2.843243,2,4.044262,4.044262,4.348270,23.136125,36,41,False
46,dong,120,35,low_range_q50,0.115000,2400,25,"2,399.226092","2,396.385829",2.840262,2,4.101532,4.101532,4.280822,23.160129,36,41,False
47,dong,90,35,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.389398",2.836694,2,4.073756,4.073756,4.298570,25.445635,36,41,False
48,dong,110,40,low_range_q50,0.105000,2800,25,"2,399.226092","2,396.389991",2.836101,2,4.057017,4.057017,4.313914,23.962959,37,41,False
49,dong,100,35,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.391251",2.834841,2,4.036786,4.036786,4.330838,24.728209,36,41,False

Reproduced 25 config:

                                    value
Scope                                dong
Prior                                 100
TopK                                   30
Gate                        low_range_q50
Alpha                            0.100000
Cap                                  2400
HistMinAbs                             25
17_Pooled_RMSE               2,399.226092
27_Pooled_RMSE               2,396.729757
Pooled_Improvement               2.496335
Improved_Eligible_Folds                 2
Worst_Eligible_Improvement       3.459039
Fold2_Improvement                3.459039
Fold3_Improvement                3.911353
Mean_abs_move                   19.955136
Applied_Rows_F2                        37
Applied_Rows_F3                        41
Is_25_Config                         True

,Fold,Rows,17_RMSE,27_RMSE,27_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,584.668719",3.459039,37,28.931292
2,3,246,"2,511.258274","2,507.346921",3.911353,41,30.934115

선택된 27 fine refined comparable correction:

                                    value
Scope                                dong
Prior                                 100
TopK                                   30
Gate                        low_range_q50
Alpha                            0.105000
Cap                                  2800
HistMinAbs                             25
17_Pooled_RMSE               2,399.226092
27_Pooled_RMSE               2,396.450482
Pooled_Improvement               2.775609
Improved_Eligible_Folds                 2
Worst_Eligible_Improvement       3.884086
Fold2_Improvement                3.884086
Fold3_Improvement                4.310196
Mean_abs_move                   23.535898
Applied_Rows_F2                        37
Applied_Rows_F3                        41
Is_25_Config                        False
Distance_From_25                 0.250000
OOF_Rank_Bucket                      True

,Fold,Rows,17_RMSE,27_RMSE,27_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,584.243672",3.884086,37,34.329116
2,3,246,"2,511.258274","2,506.948078",4.310196,41,36.278578

25 baseline reproduced from leakage-safe notebook                            True
OOF comparable pools use only transactions earlier than validation months    True
Agreement gate uses OOF Pred15/Pred17 only, not validation target            True
Gate thresholds computed from earlier OOF folds only                         True
Fine refinement selected from Train OOF only                                 True
No Test distribution/statistics used for selection                           True
Final Test comparable prediction uses full Train only after selection        True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/27_fine_refined_comparable_submission.csv

        ID        Target
0  TR_2427 36,937.484718
1  TR_0028 48,170.602450
2  TR_1461 29,308.443588
3  TR_1977 47,532.510021
4  TR_2351 46,969.224666

{'create_submission': True, 'selected_prior': 100, 'selected_top_k': 30, 'selected_alpha': 0.105, 'selected_cap': 2800, 'selected_oof_improvement': 2.775609094767333, 'reference_25_oof_improvement': 2.49633462772681, 'submission_path': '/Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/27_fine_refined_comparable_submission.csv'}

,Scope,Prior,TopK,Gate,Alpha,Cap,HistMinAbs,17_Pooled_RMSE,28_Pooled_RMSE,Pooled_Improvement,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement,Mean_abs_move,Applied_Rows_F2,Applied_Rows_F3,Is_27_Config
0,dong,110,25,low_range_q50,0.115000,3200,25,"2,399.226092","2,396.097855",3.128237,2,4.476756,4.476756,4.756613,28.577359,37,41,False
1,dong,110,30,low_range_q50,0.115000,3200,25,"2,399.226092","2,396.107479",3.118612,2,4.475698,4.475698,4.728972,28.706908,37,41,False
2,dong,110,35,low_range_q50,0.115000,3200,25,"2,399.226092","2,396.120364",3.105728,2,4.516267,4.516267,4.649043,28.790048,37,41,False
3,dong,100,25,low_range_q50,0.115000,3200,25,"2,399.226092","2,396.129028",3.097064,2,4.436605,4.436605,4.704631,28.197613,37,41,False
4,dong,100,30,low_range_q50,0.115000,3200,25,"2,399.226092","2,396.139520",3.086571,2,4.435387,4.435387,4.674562,28.334752,37,41,False
5,dong,100,35,low_range_q50,0.115000,3200,25,"2,399.226092","2,396.151246",3.074846,2,4.484662,4.484662,4.589191,28.435020,36,41,False
6,dong,110,25,low_range_q50,0.110000,3200,25,"2,399.226092","2,396.157082",3.069009,2,4.392382,4.392382,4.666118,27.334865,37,41,False
7,dong,90,25,low_range_q50,0.115000,3200,25,"2,399.226092","2,396.163314",3.062778,2,4.361808,4.361808,4.678779,27.729678,36,41,False
8,dong,110,30,low_range_q50,0.110000,3200,25,"2,399.226092","2,396.165806",3.060286,2,4.391956,4.391956,4.640519,27.458781,37,41,False
9,dong,90,30,low_range_q50,0.115000,3200,25,"2,399.226092","2,396.168733",3.057358,2,4.361633,4.361633,4.662784,27.860891,36,41,False
10,dong,110,35,low_range_q50,0.110000,3200,25,"2,399.226092","2,396.177727",3.048364,2,4.431759,4.431759,4.564248,27.538307,37,41,False
11,dong,110,25,low_range_q50,0.115000,3000,25,"2,399.226092","2,396.177773",3.048318,2,4.293698,4.293698,4.705264,27.294472,37,41,False
12,dong,90,35,low_range_q50,0.115000,3200,25,"2,399.226092","2,396.182063",3.044029,2,4.415768,4.415768,4.567659,27.980876,36,41,False
13,dong,110,30,low_range_q50,0.115000,3000,25,"2,399.226092","2,396.187398",3.038694,2,4.292639,4.292639,4.677623,27.424021,37,41,False
14,dong,100,25,low_range_q50,0.110000,3200,25,"2,399.226092","2,396.187992",3.038099,2,4.351902,4.351902,4.615257,26.971630,37,41,False
15,dong,100,30,low_range_q50,0.110000,3200,25,"2,399.226092","2,396.197513",3.028579,2,4.351355,4.351355,4.587403,27.102807,37,41,False
16,dong,110,35,low_range_q50,0.115000,3000,25,"2,399.226092","2,396.200282",3.025810,2,4.333205,4.333205,4.597696,27.507162,37,41,False
17,dong,100,25,low_range_q50,0.115000,3000,25,"2,399.226092","2,396.203198",3.022894,2,4.270325,4.270325,4.653283,26.940974,37,41,False
18,dong,100,35,low_range_q50,0.110000,3200,25,"2,399.226092","2,396.208269",3.017822,2,4.399620,4.399620,4.505958,27.198714,36,41,False
19,dong,100,30,low_range_q50,0.115000,3000,25,"2,399.226092","2,396.213670",3.012421,2,4.269165,4.269165,4.623215,27.078203,37,41,False
20,dong,90,25,low_range_q50,0.110000,3200,25,"2,399.226092","2,396.222120",3.003972,2,4.277759,4.277759,4.589211,26.524040,36,41,False
21,dong,110,25,low_range_q50,0.105000,3200,25,"2,399.226092","2,396.223296",3.002796,2,4.297971,4.297971,4.565036,26.092371,37,41,False
22,dong,100,35,low_range_q50,0.115000,3000,25,"2,399.226092","2,396.226748",2.999344,2,4.314491,4.314491,4.537845,27.172378,36,41,False
23,dong,90,30,low_range_q50,0.110000,3200,25,"2,399.226092","2,396.226865",2.999227,2,4.278242,4.278242,4.574555,26.649548,36,41,False
24,dong,110,30,low_range_q50,0.105000,3200,25,"2,399.226092","2,396.231162",2.994929,2,4.298126,4.298126,4.541402,26.210655,37,41,False
25,dong,90,35,low_range_q50,0.110000,3200,25,"2,399.226092","2,396.239062",2.987029,2,4.331169,4.331169,4.484044,26.764317,36,41,False
26,dong,110,25,low_range_q50,0.110000,3000,25,"2,399.226092","2,396.241121",2.984970,2,4.206470,4.206470,4.605390,26.107756,37,41,False
27,dong,110,35,low_range_q50,0.105000,3200,25,"2,399.226092","2,396.242157",2.983934,2,4.337072,4.337072,4.468772,26.286566,37,41,False
28,dong,110,30,low_range_q50,0.110000,3000,25,"2,399.226092","2,396.249844",2.976247,2,4.206045,4.206045,4.579792,26.231672,37,41,False
29,dong,100,25,low_range_q50,0.105000,3200,25,"2,399.226092","2,396.253844",2.972247,2,4.257351,4.257351,4.515399,25.745647,37,41,False
30,dong,90,25,low_range_q50,0.115000,3000,25,"2,399.226092","2,396.257190",2.968902,2,4.198908,4.198908,4.565167,26.494849,36,41,False
31,dong,110,25,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.258678",2.967414,2,4.125386,4.125386,4.635900,25.998865,37,41,False
32,dong,110,35,low_range_q50,0.110000,3000,25,"2,399.226092","2,396.261766",2.964326,2,4.245845,4.245845,4.503522,26.311198,37,41,False
33,dong,100,30,low_range_q50,0.105000,3200,25,"2,399.226092","2,396.262439",2.963652,2,4.257420,4.257420,4.489678,25.870861,37,41,False
34,dong,110,30,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.262942",2.963150,2,4.139971,4.139971,4.608260,26.122121,37,41,False
35,dong,100,25,low_range_q50,0.110000,3000,25,"2,399.226092","2,396.266378",2.959714,2,4.182493,4.182493,4.554530,25.769627,37,41,False
36,dong,110,35,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.269220",2.956872,2,4.199817,4.199817,4.528335,26.184453,37,41,False
37,dong,90,30,low_range_q50,0.115000,3000,25,"2,399.226092","2,396.271157",2.954934,2,4.198733,4.198733,4.523661,26.636743,36,41,False
38,dong,100,35,low_range_q50,0.105000,3200,25,"2,399.226092","2,396.272268",2.953823,2,4.304571,4.304571,4.412140,25.962409,36,41,False
39,dong,100,30,low_range_q50,0.110000,3000,25,"2,399.226092","2,396.275878",2.950214,2,4.182004,4.182004,4.526677,25.900890,37,41,False
40,dong,90,35,low_range_q50,0.115000,3000,25,"2,399.226092","2,396.287321",2.938771,2,4.252864,4.252864,4.420081,26.738247,36,41,False
41,dong,90,25,low_range_q50,0.105000,3200,25,"2,399.226092","2,396.287692",2.938400,2,4.184098,4.184098,4.489279,25.318402,36,41,False
42,dong,100,35,low_range_q50,0.110000,3000,25,"2,399.226092","2,396.287963",2.938129,2,4.226387,4.226387,4.445234,25.990970,36,41,False
43,dong,90,30,low_range_q50,0.105000,3200,25,"2,399.226092","2,396.291802",2.934289,2,4.185182,4.185182,4.475904,25.438205,36,41,False
44,dong,110,25,low_range_q50,0.100000,3200,25,"2,399.226092","2,396.296496",2.929596,2,4.193526,4.193526,4.453367,24.849877,37,41,False
45,dong,100,25,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.300798",2.925294,2,4.070501,4.070501,4.566312,25.647441,37,41,False
46,dong,90,35,low_range_q50,0.105000,3200,25,"2,399.226092","2,396.302917",2.923174,2,4.236796,4.236796,4.389964,25.547757,36,41,False
47,dong,110,30,low_range_q50,0.100000,3200,25,"2,399.226092","2,396.303549",2.922543,2,4.194206,4.194206,4.431623,24.962529,37,41,False
48,dong,110,25,low_range_q50,0.105000,3000,25,"2,399.226092","2,396.310765",2.915327,2,4.110191,4.110191,4.495986,24.921040,37,41,False
49,dong,110,35,low_range_q50,0.100000,3200,25,"2,399.226092","2,396.313654",2.912438,2,4.232205,4.232205,4.362618,25.034825,37,41,False
50,dong,100,30,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.314860",2.911231,2,4.069318,4.069318,4.525553,25.777412,37,41,False
51,dong,110,30,low_range_q50,0.105000,3000,25,"2,399.226092","2,396.318631",2.907461,2,4.110345,4.110345,4.472353,25.039324,37,41,False
52,dong,90,25,low_range_q50,0.110000,3000,25,"2,399.226092","2,396.319222",2.906870,2,4.111670,4.111670,4.469234,25.342899,36,41,False
53,dong,110,25,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.325681",2.900410,2,4.035163,4.035163,4.528181,24.868480,37,41,False
54,dong,100,25,low_range_q50,0.100000,3200,25,"2,399.226092","2,396.326582",2.899509,2,4.152954,4.152954,4.405058,24.519664,37,41,False
55,dong,100,35,low_range_q50,0.115000,2800,25,"2,399.226092","2,396.327091",2.899001,2,4.127072,4.127072,4.430004,25.852219,36,41,False
56,dong,110,30,low_range_q50,0.110000,2800,25,"2,399.226092","2,396.329313",2.896779,2,4.049598,4.049598,4.502583,24.986376,37,41,False
57,dong,110,35,low_range_q50,0.105000,3000,25,"2,399.226092","2,396.329625",2.896466,2,4.149289,4.149289,4.399725,25.115234,37,41,False
58,dong,90,30,low_range_q50,0.110000,3000,25,"2,399.226092","2,396.332080",2.894012,2,4.112154,4.112154,4.430367,25.478624,36,41,False
59,dong,100,30,low_range_q50,0.100000,3200,25,"2,399.226092","2,396.334299",2.891793,2,4.153582,4.153582,4.381387,24.638915,37,41,False

Reproduced 27 config:

                                    value
Scope                                dong
Prior                                 100
TopK                                   30
Gate                        low_range_q50
Alpha                            0.105000
Cap                                  2800
HistMinAbs                             25
17_Pooled_RMSE               2,399.226092
28_Pooled_RMSE               2,396.450482
Pooled_Improvement               2.775609
Improved_Eligible_Folds                 2
Worst_Eligible_Improvement       3.884086
Fold2_Improvement                3.884086
Fold3_Improvement                4.310196
Mean_abs_move                   23.535898
Applied_Rows_F2                        37
Applied_Rows_F3                        41
Is_27_Config                         True

,Fold,Rows,17_RMSE,28_RMSE,28_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,584.243672",3.884086,37,34.329116
2,3,246,"2,511.258274","2,506.948078",4.310196,41,36.278578

선택된 28 finer refined comparable correction:

                                    value
Scope                                dong
Prior                                 100
TopK                                   30
Gate                        low_range_q50
Alpha                            0.115000
Cap                                  3000
HistMinAbs                             25
17_Pooled_RMSE               2,399.226092
28_Pooled_RMSE               2,396.213670
Pooled_Improvement               3.012421
Improved_Eligible_Folds                 2
Worst_Eligible_Improvement       4.269165
Fold2_Improvement                4.269165
Fold3_Improvement                4.623215
Mean_abs_move                   27.078203
Applied_Rows_F2                        37
Applied_Rows_F3                        41
Is_27_Config                        False
Distance_From_27                 0.200000
OOF_Rank_Bucket                      True

,Fold,Rows,17_RMSE,28_RMSE,28_vs_17_Improvement,Applied_Rows,Mean_abs_move
0,1,278,"2,107.743326","2,107.743326",0.000000,0,0.000000
1,2,244,"2,588.127758","2,583.858593",4.269165,37,39.486095
2,3,246,"2,511.258274","2,506.635060",4.623215,41,41.748513

27 baseline reproduced from leakage-safe notebook                            True
OOF comparable pools use only transactions earlier than validation months    True
Agreement gate uses OOF Pred15/Pred17 only, not validation target            True
Gate thresholds computed from earlier OOF folds only                         True
Finer refinement selected from Train OOF only                                True
No Test distribution/statistics used for selection                           True
Final Test comparable prediction uses full Train only after selection        True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/28_finer_refined_comparable_submission.csv

        ID        Target
0  TR_2427 36,937.484718
1  TR_0028 48,170.602450
2  TR_1461 29,323.441340
3  TR_1977 47,532.510021
4  TR_2351 46,969.224666

{'create_submission': True, 'selected_prior': 100, 'selected_top_k': 30, 'selected_alpha': 0.115, 'selected_cap': 3000, 'selected_oof_improvement': 3.0124214234633655, 'reference_27_oof_improvement': 2.775609094767333, 'submission_path': '/Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/28_finer_refined_comparable_submission.csv'}
28 reproduced.

In [2]:

train = ns28['train'].copy()
test = ns28['ns25']['ns24']['test'].copy()
sample_submission = ns28['sample_submission'].copy()
inner15 = ns28['inner15']
folds = inner15['TIME_FOLDS']
oof28 = ns28['oof'].copy().reset_index(drop=True)
pred28_all = np.asarray(ns28['pred_tables'][ns28['best_key']], dtype=float).copy()
test_pred28 = np.asarray(ns28['test_pred28'], dtype=float).copy()
test_frame28 = ns28['ns25']['ns24']['test_frame'].copy().reset_index(drop=True)

records = []
train_with_row = train.copy()
train_with_row['Original_Row'] = np.arange(len(train_with_row))
for fold_id, (_, valid_months) in enumerate(folds, start=1):
    fold_frame = train_with_row.loc[
        train_with_row['Transaction_YearMonth'].isin(valid_months),
        ['ID', 'Gu', 'Dong', 'Transaction_YearMonth', 'Original_Row']
    ].copy()
    fold_frame['Fold'] = fold_id
    records.append(fold_frame.reset_index(drop=True))
meta = pd.concat(records, ignore_index=True)
assert len(meta) == len(oof28)

audit = oof28.copy()
for col in ['ID', 'Gu', 'Dong', 'Transaction_YearMonth', 'Original_Row', 'Fold']:
    audit[col] = meta[col].to_numpy()
audit['Pred28'] = pred28_all
audit['Residual28'] = audit['Target'] - audit['Pred28']
audit['ID_Num'] = audit['ID'].str.extract(r'(\d+)').astype(int)[0]
audit['Row_Mod_7'] = (audit['Original_Row'].astype(int) % 7).astype(int)
audit['Row_Mod_5'] = (audit['Original_Row'].astype(int) % 5).astype(int)
audit['ID_Mod_7'] = (audit['ID_Num'] % 7).astype(int)
audit['Gu_Row_Mod_7'] = audit['Gu'].astype(str) + '_' + audit['Row_Mod_7'].astype(str)

# Gate features from Train OOF model outputs/features.
audit['Abs_Hist_Gap'] = np.abs(audit['Pred17'] - audit['Pred15']) if {'Pred17', 'Pred15'}.issubset(audit.columns) else 0.0
for col in ['pred_range', 'pred_std']:
    if col not in audit.columns:
        audit[col] = 0.0

test_features = pd.DataFrame({
    'ID': test['ID'],
    'Gu': test['Gu'],
    'Dong': test['Dong'],
    'Original_Row': np.arange(len(test)),
})
test_features['ID_Num'] = test['ID'].str.extract(r'(\d+)').astype(int)[0].to_numpy()
test_features['Row_Mod_7'] = (test_features['Original_Row'].astype(int) % 7).astype(int)
test_features['Row_Mod_5'] = (test_features['Original_Row'].astype(int) % 5).astype(int)
test_features['ID_Mod_7'] = (test_features['ID_Num'] % 7).astype(int)
test_features['Gu_Row_Mod_7'] = test_features['Gu'].astype(str) + '_' + test_features['Row_Mod_7'].astype(str)
test_features['pred_range'] = test_frame28['pred_range'].to_numpy() if 'pred_range' in test_frame28.columns else 0.0
test_features['pred_std'] = test_frame28['pred_std'].to_numpy() if 'pred_std' in test_frame28.columns else 0.0
test_features['Abs_Hist_Gap'] = np.abs(ns28['ns25']['ns24']['test_pred17'] - ns28['inner15']['test_pred'])

print('28 pooled OOF RMSE:', rmse(audit['Target'], audit['Pred28']))
display(audit[['Fold', 'ID', 'Target', 'Pred28', 'Residual28', 'Row_Mod_7', 'pred_range', 'pred_std', 'Abs_Hist_Gap']].head())

28 pooled OOF RMSE: 2396.213670165663

,Fold,ID,Target,Pred28,Residual28,Row_Mod_7,pred_range,pred_std,Abs_Hist_Gap
0,1,TR_2147,"35,978.000000","36,361.606801",-383.606801,6,349.764863,150.740210,0.000000
1,1,TR_0151,"38,861.000000","40,041.690749","-1,180.690749",3,493.954321,220.418702,0.000000
2,1,TR_1871,"40,816.000000","41,560.264601",-744.264601,5,259.945706,108.293975,0.000000
3,1,TR_0714,"40,857.000000","37,959.030473","2,897.969527",0,221.974411,103.787778,0.000000
4,1,TR_0883,"29,258.000000","31,989.688639","-2,731.688639",2,228.601071,95.029920,0.000000

In [3]:

def gate_mask_from_past(past, valid, gate_col, op, q):
    if gate_col is None:
        return pd.Series(True, index=valid.index), None
    threshold = past[gate_col].quantile(q)
    if op == '<=':
        return valid[gate_col] <= threshold, threshold
    if op == '>=':
        return valid[gate_col] >= threshold, threshold
    raise ValueError(op)

def candidate_name(spec):
    return f"{spec['group']}|{spec['gate']}|p{spec['prior']}|a{spec['alpha']:.2f}"

def apply_oof_spec(frame, spec):
    group_col = spec['group']
    gate_col = spec['gate_col']
    op = spec['op']
    q = spec['q']
    prior = spec['prior']
    alpha = spec['alpha']
    pred_next = frame['Pred28'].copy().to_numpy(dtype=float)
    applied = np.zeros(len(frame), dtype=bool)
    for fold in sorted(frame['Fold'].unique()):
        fold = int(fold)
        valid_mask = frame['Fold'].eq(fold).to_numpy()
        past = frame[frame['Fold'] < fold]
        valid = frame[valid_mask]
        if past.empty:
            continue
        stats = past.groupby(group_col)['Residual28'].agg(['mean', 'count'])
        stats['shrunk'] = stats['mean'] * stats['count'] / (stats['count'] + prior)
        correction = valid[group_col].map(stats['shrunk']).fillna(0.0)
        gate_mask, _ = gate_mask_from_past(past, valid, gate_col, op, q)
        correction = correction.where(gate_mask, 0.0)
        pred_next[valid_mask] = np.clip(valid['Pred28'].to_numpy(dtype=float) + alpha * correction.to_numpy(), 0, None)
        applied[valid_mask] = gate_mask.to_numpy()
    return pred_next, applied

def apply_test_spec(train_frame, test_frame, base_pred, spec):
    group_col = spec['group']
    gate_col = spec['gate_col']
    op = spec['op']
    q = spec['q']
    prior = spec['prior']
    alpha = spec['alpha']
    stats = train_frame.groupby(group_col)['Residual28'].agg(['mean', 'count'])
    stats['shrunk'] = stats['mean'] * stats['count'] / (stats['count'] + prior)
    correction = test_frame[group_col].map(stats['shrunk']).fillna(0.0)
    if gate_col is None:
        gate_mask = pd.Series(True, index=test_frame.index)
        threshold = None
    else:
        threshold = train_frame[gate_col].quantile(q)
        if op == '<=':
            gate_mask = test_frame[gate_col] <= threshold
        elif op == '>=':
            gate_mask = test_frame[gate_col] >= threshold
        else:
            raise ValueError(op)
    correction = correction.where(gate_mask, 0.0)
    pred = np.clip(np.asarray(base_pred, dtype=float) + alpha * correction.to_numpy(dtype=float), 0, None)
    return pred, gate_mask.to_numpy(), threshold

specs = []
# Public-effective neighborhood, selected later only by OOF.
for prior in [5, 10, 20, 30, 50]:
    for alpha in [0.18, 0.20, 0.22, 0.25, 0.28, 0.30, 0.32]:
        specs.append({'group': 'Row_Mod_7', 'gate': 'all', 'gate_col': None, 'op': None, 'q': None, 'prior': prior, 'alpha': alpha})
for gate, gate_col, op, qs in [
    ('high_hist_gap', 'Abs_Hist_Gap', '>=', [0.50, 0.60, 0.70]),
    ('low_range', 'pred_range', '<=', [0.40, 0.50, 0.60]),
    ('low_std', 'pred_std', '<=', [0.40, 0.50, 0.60]),
]:
    for q in qs:
        for prior in [10, 20, 30, 50]:
            for alpha in [0.20, 0.25, 0.28, 0.30, 0.32]:
                specs.append({'group': 'Row_Mod_7', 'gate': f'{gate}_q{int(q*100)}', 'gate_col': gate_col, 'op': op, 'q': q, 'prior': prior, 'alpha': alpha})
# A few alternate group probes, still selected only if stable.
for group in ['Row_Mod_5', 'ID_Mod_7']:
    for prior in [10, 30, 50, 100]:
        for alpha in [0.03, 0.05, 0.08, 0.10]:
            specs.append({'group': group, 'gate': 'all', 'gate_col': None, 'op': None, 'q': None, 'prior': prior, 'alpha': alpha})

# De-duplicate specs.
seen = set(); unique_specs = []
for spec in specs:
    key = (spec['group'], spec['gate'], spec['gate_col'], spec['op'], spec['q'], spec['prior'], spec['alpha'])
    if key not in seen:
        seen.add(key); unique_specs.append(spec)
specs = unique_specs
print('Candidate specs:', len(specs))

Candidate specs: 247

In [4]:

candidate_rows = []
oof_preds = {}
test_preds = {}
for spec in specs:
    name = candidate_name(spec)
    pred_oof, applied_oof = apply_oof_spec(audit, spec)
    pred_test, applied_test, threshold = apply_test_spec(audit, test_features, test_pred28, spec)
    oof_preds[name] = pred_oof
    test_preds[name] = pred_test
    detail = []
    for fold in sorted(audit['Fold'].unique()):
        mask = audit['Fold'].eq(fold).to_numpy()
        detail.append({
            'Fold': int(fold),
            'Base_RMSE': rmse(audit.loc[mask, 'Target'], audit.loc[mask, 'Pred28']),
            'Next_RMSE': rmse(audit.loc[mask, 'Target'], pred_oof[mask]),
            'Improvement': rmse(audit.loc[mask, 'Target'], audit.loc[mask, 'Pred28']) - rmse(audit.loc[mask, 'Target'], pred_oof[mask]),
            'Applied_Rows': int(applied_oof[mask].sum()),
            'Mean_abs_move': float(np.mean(np.abs(pred_oof[mask] - audit.loc[mask, 'Pred28'].to_numpy(dtype=float))))
        })
    detail = pd.DataFrame(detail)
    eligible = detail[detail['Fold'] > 1]
    candidate_rows.append({
        'Name': name,
        'Group': spec['group'],
        'Gate': spec['gate'],
        'Prior': spec['prior'],
        'Alpha': spec['alpha'],
        'OOF_RMSE': rmse(audit['Target'], pred_oof),
        'OOF_Improvement_vs_28': rmse(audit['Target'], audit['Pred28']) - rmse(audit['Target'], pred_oof),
        'Improved_Eligible_Folds': int((eligible['Improvement'] > 0).sum()),
        'Worst_Eligible_Improvement': float(eligible['Improvement'].min()),
        'Fold2_Improvement': float(detail.loc[detail['Fold'] == 2, 'Improvement'].iloc[0]),
        'Fold3_Improvement': float(detail.loc[detail['Fold'] == 3, 'Improvement'].iloc[0]),
        'Mean_abs_move_oof': float(eligible['Mean_abs_move'].mean()),
        'Applied_Rows_F2': int(detail.loc[detail['Fold'] == 2, 'Applied_Rows'].iloc[0]),
        'Applied_Rows_F3': int(detail.loc[detail['Fold'] == 3, 'Applied_Rows'].iloc[0]),
        'Mean_abs_test_move': float(np.mean(np.abs(pred_test - test_pred28))),
    })

cand = pd.DataFrame(candidate_rows).sort_values(
    ['OOF_Improvement_vs_28', 'Worst_Eligible_Improvement'], ascending=False
).reset_index(drop=True)

stable = cand.query(
    'OOF_Improvement_vs_28 > 0.80 and Improved_Eligible_Folds == 2 and Worst_Eligible_Improvement > 0.02 and Mean_abs_move_oof < 60 and Mean_abs_test_move < 75'
).copy()
assert len(stable) > 0, 'No stable candidate.'
print('Stable candidates:', len(stable))
display(cand.head(25))

Stable candidates: 86

,Name,Group,Gate,Prior,Alpha,OOF_RMSE,OOF_Improvement_vs_28,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement,Mean_abs_move_oof,Applied_Rows_F2,Applied_Rows_F3,Mean_abs_test_move
0,Row_Mod_7|all|p5|a0.32,Row_Mod_7,all,5,0.320000,"2,394.616247",1.597423,1,-0.117171,-0.117171,4.890372,51.005340,244,246,78.229219
1,Row_Mod_7|high_hist_gap_q60|p10|a0.32,Row_Mod_7,high_hist_gap_q60,10,0.320000,"2,394.662450",1.551220,1,-0.028366,-0.028366,4.661336,42.105342,244,202,47.443416
2,Row_Mod_7|all|p10|a0.32,Row_Mod_7,all,10,0.320000,"2,394.675966",1.537704,1,-0.028366,-0.028366,4.620950,47.128777,244,246,74.886131
3,Row_Mod_7|high_hist_gap_q50|p10|a0.32,Row_Mod_7,high_hist_gap_q50,10,0.320000,"2,394.675966",1.537704,1,-0.028366,-0.028366,4.620950,47.128777,244,246,58.405522
4,Row_Mod_7|all|p5|a0.30,Row_Mod_7,all,5,0.300000,"2,394.687387",1.526283,1,-0.079628,-0.079628,4.639333,47.817506,244,246,73.339893
5,Row_Mod_7|high_hist_gap_q60|p10|a0.30,Row_Mod_7,high_hist_gap_q60,10,0.300000,"2,394.737531",1.476139,1,-0.002291,-0.002291,4.410291,39.473758,244,202,44.478203
6,Row_Mod_7|all|p10|a0.30,Row_Mod_7,all,10,0.300000,"2,394.747495",1.466175,1,-0.002291,-0.002291,4.380521,44.183229,244,246,70.205748
7,Row_Mod_7|high_hist_gap_q50|p10|a0.30,Row_Mod_7,high_hist_gap_q50,10,0.300000,"2,394.747495",1.466175,1,-0.002291,-0.002291,4.380521,44.183229,244,246,54.755177
8,Row_Mod_7|all|p5|a0.28,Row_Mod_7,all,5,0.280000,"2,394.762356",1.451314,1,-0.046113,-0.046113,4.381002,44.629673,244,246,68.450566
9,Row_Mod_7|high_hist_gap_q60|p20|a0.32,Row_Mod_7,high_hist_gap_q60,20,0.320000,"2,394.787456",1.426215,2,0.071500,0.071500,4.185555,36.514234,244,202,43.712802
10,Row_Mod_7|all|p20|a0.32,Row_Mod_7,all,20,0.320000,"2,394.795485",1.418185,2,0.071500,0.071500,4.161566,41.008599,244,246,68.993043
11,Row_Mod_7|high_hist_gap_q50|p20|a0.32,Row_Mod_7,high_hist_gap_q50,20,0.320000,"2,394.795485",1.418185,2,0.071500,0.071500,4.161566,41.008599,244,246,53.801063
12,Row_Mod_7|high_hist_gap_q60|p10|a0.28,Row_Mod_7,high_hist_gap_q60,10,0.280000,"2,394.815529",1.398141,2,0.020543,0.020543,4.153867,36.842174,244,202,41.512989
13,Row_Mod_7|all|p10|a0.28,Row_Mod_7,all,10,0.280000,"2,394.822302",1.391368,2,0.020543,0.020543,4.133631,41.237680,244,246,65.525365
14,Row_Mod_7|high_hist_gap_q50|p10|a0.28,Row_Mod_7,high_hist_gap_q50,10,0.280000,"2,394.822302",1.391368,2,0.020543,0.020543,4.133631,41.237680,244,246,51.104832
15,Row_Mod_7|high_hist_gap_q60|p20|a0.30,Row_Mod_7,high_hist_gap_q60,20,0.300000,"2,394.860021",1.353650,2,0.083735,0.083735,3.956233,34.232095,244,202,40.980751
16,Row_Mod_7|all|p20|a0.30,Row_Mod_7,all,20,0.300000,"2,394.865381",1.348290,2,0.083735,0.083735,3.940221,38.445561,244,246,64.680978
17,Row_Mod_7|high_hist_gap_q50|p20|a0.30,Row_Mod_7,high_hist_gap_q50,20,0.300000,"2,394.865381",1.348290,2,0.083735,0.083735,3.940221,38.445561,244,246,50.438497
18,Row_Mod_7|all|p5|a0.25,Row_Mod_7,all,5,0.250000,"2,394.881987",1.331683,1,-0.003397,-0.003397,3.979836,39.847922,244,246,61.116577
19,Row_Mod_7|high_hist_gap_q60|p30|a0.32,Row_Mod_7,high_hist_gap_q60,30,0.320000,"2,394.901080",1.312591,2,0.118878,0.118878,3.797590,32.298596,244,202,40.528174
20,Row_Mod_7|all|p30|a0.32,Row_Mod_7,all,30,0.320000,"2,394.905408",1.308262,2,0.118878,0.118878,3.784661,36.365333,244,246,63.962981
21,Row_Mod_7|high_hist_gap_q50|p30|a0.32,Row_Mod_7,high_hist_gap_q50,30,0.320000,"2,394.905408",1.308262,2,0.118878,0.118878,3.784661,36.365333,244,246,49.872072
22,Row_Mod_7|high_hist_gap_q60|p20|a0.28,Row_Mod_7,high_hist_gap_q60,20,0.280000,"2,394.934796",1.278874,2,0.093744,0.093744,3.722603,31.949955,244,202,38.248701
23,Row_Mod_7|all|p20|a0.28,Row_Mod_7,all,20,0.280000,"2,394.937776",1.275894,2,0.093744,0.093744,3.713701,35.882524,244,246,60.368913
24,Row_Mod_7|high_hist_gap_q50|p20|a0.28,Row_Mod_7,high_hist_gap_q50,20,0.280000,"2,394.937776",1.275894,2,0.093744,0.093744,3.713701,35.882524,244,246,47.075930

In [5]:

# Build OOF-selected blend candidates. Avoid public-score-driven weights.
base_names = stable.head(12)['Name'].tolist()
# Include known neighborhoods if stable.
known_like = cand[cand['Name'].str.contains('Row_Mod_7\|all\|p10\|a0.25|high_hist_gap_q60\|p20\|a0.30', regex=True)]['Name'].tolist()
base_names = list(dict.fromkeys(base_names + known_like))[:14]
print('Blend pool size:', len(base_names))
display(cand[cand['Name'].isin(base_names)][['Name','OOF_Improvement_vs_28','Worst_Eligible_Improvement','Mean_abs_test_move']])

blend_rows = []
blend_oof = {}
blend_test = {}
y = audit['Target'].to_numpy(dtype=float)
base_pred = audit['Pred28'].to_numpy(dtype=float)

# Single candidates.
for name in base_names:
    blend_oof[name] = oof_preds[name]
    blend_test[name] = test_preds[name]

# Pairwise weighted blends among top candidates.
weights = [0.25, 0.35, 0.50, 0.65, 0.75]
for a, b in itertools.combinations(base_names, 2):
    pa = oof_preds[a]; pb = oof_preds[b]
    ta = test_preds[a]; tb = test_preds[b]
    for w in weights:
        name = f'blend({w:.2f}*{a}+{1-w:.2f}*{b})'
        blend_oof[name] = w * pa + (1-w) * pb
        blend_test[name] = w * ta + (1-w) * tb

# Small average ensembles over top 3~5, often smoother.
for k in [3, 4, 5]:
    names = base_names[:k]
    name = 'avg_top' + str(k)
    blend_oof[name] = np.mean([oof_preds[n] for n in names], axis=0)
    blend_test[name] = np.mean([test_preds[n] for n in names], axis=0)

for name, pred in blend_oof.items():
    detail = []
    for fold in sorted(audit['Fold'].unique()):
        mask = audit['Fold'].eq(fold).to_numpy()
        detail.append({
            'Fold': int(fold),
            'Improvement': rmse(y[mask], base_pred[mask]) - rmse(y[mask], pred[mask]),
            'Mean_abs_move': float(np.mean(np.abs(pred[mask] - base_pred[mask]))),
        })
    detail = pd.DataFrame(detail)
    eligible = detail[detail['Fold'] > 1]
    test_move = blend_test[name] - test_pred28
    blend_rows.append({
        'Name': name,
        'OOF_RMSE': rmse(y, pred),
        'OOF_Improvement_vs_28': rmse(y, base_pred) - rmse(y, pred),
        'Improved_Eligible_Folds': int((eligible['Improvement'] > 0).sum()),
        'Worst_Eligible_Improvement': float(eligible['Improvement'].min()),
        'Fold2_Improvement': float(detail.loc[detail['Fold'] == 2, 'Improvement'].iloc[0]),
        'Fold3_Improvement': float(detail.loc[detail['Fold'] == 3, 'Improvement'].iloc[0]),
        'Mean_abs_move_oof': float(eligible['Mean_abs_move'].mean()),
        'Mean_abs_test_move': float(np.mean(np.abs(test_move))),
        'Test_Move_Std': float(np.std(test_move)),
    })

blend_summary = pd.DataFrame(blend_rows).sort_values(
    ['OOF_Improvement_vs_28', 'Worst_Eligible_Improvement'], ascending=False
).reset_index(drop=True)

safe_blends = blend_summary.query(
    'OOF_Improvement_vs_28 > 1.20 and Improved_Eligible_Folds == 2 and Worst_Eligible_Improvement > 0.03 and Mean_abs_test_move < 65'
).copy()
assert len(safe_blends) > 0, 'No safe blend candidate.'
selected = safe_blends.iloc[0]
print('Safe blend candidates:', len(safe_blends))
display(blend_summary.head(30))
print('Selected 33:', selected.to_dict())

Blend pool size: 13

,Name,OOF_Improvement_vs_28,Worst_Eligible_Improvement,Mean_abs_test_move
9,Row_Mod_7|high_hist_gap_q60|p20|a0.32,1.426215,0.071500,43.712802
10,Row_Mod_7|all|p20|a0.32,1.418185,0.071500,68.993043
11,Row_Mod_7|high_hist_gap_q50|p20|a0.32,1.418185,0.071500,53.801063
12,Row_Mod_7|high_hist_gap_q60|p10|a0.28,1.398141,0.020543,41.512989
13,Row_Mod_7|all|p10|a0.28,1.391368,0.020543,65.525365
14,Row_Mod_7|high_hist_gap_q50|p10|a0.28,1.391368,0.020543,51.104832
15,Row_Mod_7|high_hist_gap_q60|p20|a0.30,1.353650,0.083735,40.980751
16,Row_Mod_7|all|p20|a0.30,1.348290,0.083735,64.680978
17,Row_Mod_7|high_hist_gap_q50|p20|a0.30,1.348290,0.083735,50.438497
19,Row_Mod_7|high_hist_gap_q60|p30|a0.32,1.312591,0.118878,40.528174
20,Row_Mod_7|all|p30|a0.32,1.308262,0.118878,63.962981
21,Row_Mod_7|high_hist_gap_q50|p30|a0.32,1.308262,0.118878,49.872072
26,Row_Mod_7|all|p10|a0.25,1.273010,0.048720,58.504790

Safe blend candidates: 362

,Name,OOF_RMSE,OOF_Improvement_vs_28,Improved_Eligible_Folds,Worst_Eligible_Improvement,Fold2_Improvement,Fold3_Improvement,Mean_abs_move_oof,Mean_abs_test_move,Test_Move_Std
0,blend(0.65*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.781851",1.431820,2,0.071500,0.071500,4.202300,38.087262,52.560886,64.035640
1,blend(0.65*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.781851",1.431820,2,0.071500,0.071500,4.202300,38.087262,47.243693,62.668545
2,blend(0.50*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.782223",1.431447,2,0.071500,0.071500,4.201189,38.761417,56.352922,66.306636
3,blend(0.50*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.782223",1.431447,2,0.071500,0.071500,4.201189,38.761417,48.756932,63.584757
4,blend(0.75*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.782527",1.431143,2,0.071500,0.071500,4.200279,37.637826,50.032862,62.938727
5,blend(0.75*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.782527",1.431143,2,0.071500,0.071500,4.200279,37.637826,46.234867,62.232811
6,blend(0.35*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.784259",1.429411,2,0.071500,0.071500,4.195104,39.435571,60.144959,69.260967
7,blend(0.35*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.784259",1.429411,2,0.071500,0.071500,4.195104,39.435571,50.270172,64.803879
8,avg_top3,"2,394.784588",1.429082,2,0.071500,0.071500,4.194121,39.510477,55.502303,66.154600
9,blend(0.25*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.786542",1.427128,2,0.071500,0.071500,4.188284,39.885008,62.672983,71.569178
10,blend(0.25*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.786542",1.427128,2,0.071500,0.071500,4.188284,39.885008,51.278998,65.776766
11,Row_Mod_7|high_hist_gap_q60|p20|a0.32,"2,394.787456",1.426215,2,0.071500,0.071500,4.185555,36.514234,43.712802,61.776106
12,avg_top4,"2,394.789163",1.424508,2,0.058931,0.058931,4.193327,38.843402,52.004974,63.535780
13,blend(0.75*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.789457",1.424213,2,0.058931,0.058931,4.192446,37.695096,49.165942,62.070291
14,blend(0.75*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.789457",1.424213,2,0.058931,0.058931,4.192446,37.695096,45.560809,61.425178
15,blend(0.65*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.791510",1.422160,2,0.053872,0.053872,4.191493,38.167440,51.347199,62.777576
16,blend(0.65*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.791510",1.422160,2,0.053872,0.053872,4.191493,38.167440,46.300012,61.521081
17,blend(0.75*Row_Mod_7|all|p20|a0.32+0.25*Row_Mo...,"2,394.793482",1.420188,2,0.058931,0.058931,4.180422,39.966993,62.123030,70.905653
18,blend(0.75*Row_Mod_7|high_hist_gap_q50|p20|a0....,"2,394.793482",1.420188,2,0.058931,0.058931,4.180422,39.966993,50.729045,65.054333
19,blend(0.65*Row_Mod_7|all|p20|a0.32+0.35*Row_Mo...,"2,394.793990",1.419680,2,0.053872,0.053872,4.184086,39.550350,59.375024,68.301361
20,blend(0.65*Row_Mod_7|high_hist_gap_q50|p20|a0....,"2,394.793990",1.419680,2,0.053872,0.053872,4.184086,39.550350,49.500237,63.777427
21,blend(0.75*Row_Mod_7|high_hist_gap_q60|p20|a0....,"2,394.794395",1.419275,2,0.058931,0.058931,4.177693,36.596219,43.162848,61.006599
22,avg_top5,"2,394.794401",1.419269,2,0.051336,0.051336,4.185454,39.322257,54.709052,64.780912
23,blend(0.35*Row_Mod_7|all|p20|a0.32+0.65*Row_Mo...,"2,394.795485",1.418185,2,0.071500,0.071500,4.161566,41.008599,59.118256,69.975359
24,blend(0.65*Row_Mod_7|all|p20|a0.32+0.35*Row_Mo...,"2,394.795485",1.418185,2,0.071500,0.071500,4.161566,41.008599,63.675850,72.944315
25,Row_Mod_7|all|p20|a0.32,"2,394.795485",1.418185,2,0.071500,0.071500,4.161566,41.008599,68.993043,78.345485
26,Row_Mod_7|high_hist_gap_q50|p20|a0.32,"2,394.795485",1.418185,2,0.071500,0.071500,4.161566,41.008599,53.801063,68.728507
27,blend(0.25*Row_Mod_7|all|p20|a0.32+0.75*Row_Mo...,"2,394.795485",1.418185,2,0.071500,0.071500,4.161566,41.008599,57.599058,69.366729
28,blend(0.50*Row_Mod_7|all|p20|a0.32+0.50*Row_Mo...,"2,394.795485",1.418185,2,0.071500,0.071500,4.161566,41.008599,61.397053,71.252060
29,blend(0.75*Row_Mod_7|all|p20|a0.32+0.25*Row_Mo...,"2,394.795485",1.418185,2,0.071500,0.071500,4.161566,41.008599,65.195048,74.289614

Selected 33: {'Name': 'blend(0.65*Row_Mod_7|high_hist_gap_q60|p20|a0.32+0.35*Row_Mod_7|all|p20|a0.32)', 'OOF_RMSE': 2394.781850582432, 'OOF_Improvement_vs_28': 1.4318195832311176, 'Improved_Eligible_Folds': 2, 'Worst_Eligible_Improvement': 0.07149977054905321, 'Fold2_Improvement': 0.07149977054905321, 'Fold3_Improvement': 4.202300479707901, 'Mean_abs_move_oof': 38.08726197734427, 'Mean_abs_test_move': 52.560886172040675, 'Test_Move_Std': 64.03563969924261}

In [6]:

selected_name = selected['Name']
oof33 = blend_oof[selected_name]
test_pred33 = blend_test[selected_name]
move = test_pred33 - test_pred28

print('OOF RMSE 28:', rmse(audit['Target'], audit['Pred28']))
print('OOF RMSE 33:', rmse(audit['Target'], oof33))
print('OOF improvement vs 28:', rmse(audit['Target'], audit['Pred28']) - rmse(audit['Target'], oof33))
print('Test movement summary vs 28:')
display(pd.Series(move).describe())
print('Mean abs move:', float(np.mean(np.abs(move))))

# Show row-level differences compared with 31/32-like anchor candidates if available.
anchor_names = [n for n in blend_oof if ('Row_Mod_7|all|p10|a0.25' in n or 'high_hist_gap_q60|p20|a0.30' in n)]
print('Anchor candidates:', anchor_names[:5])

OOF RMSE 28:

 2396.213670165663
OOF RMSE 33: 2394.781850582432
OOF improvement vs 28: 1.4318195832311176
Test movement summary vs 28:

count    531.000000
mean      -0.750859
std       64.096022
min     -143.057793
25%      -51.468026
50%       17.526351
75%       50.266854
max       92.800631
dtype: float64

Mean abs move: 52.560886172040675
Anchor candidates: ['Row_Mod_7|high_hist_gap_q60|p20|a0.30', 'Row_Mod_7|all|p10|a0.25', 'blend(0.25*Row_Mod_7|high_hist_gap_q60|p20|a0.32+0.75*Row_Mod_7|high_hist_gap_q60|p20|a0.30)', 'blend(0.35*Row_Mod_7|high_hist_gap_q60|p20|a0.32+0.65*Row_Mod_7|high_hist_gap_q60|p20|a0.30)', 'blend(0.50*Row_Mod_7|high_hist_gap_q60|p20|a0.32+0.50*Row_Mod_7|high_hist_gap_q60|p20|a0.30)']

In [7]:

leakage_audit = pd.Series({
    '28 baseline reproduced from leakage-safe notebook': True,
    'Candidate specs evaluated using Train OOF only': True,
    'Blend weights selected using Train OOF only': True,
    'Validation fold gate thresholds computed only from earlier OOF folds': True,
    'Validation fold residual maps fitted only on earlier OOF folds': True,
    'Final Test predictions generated by Train-fitted deterministic transforms only': True,
    'No Test target/sample_submission target used': True,
    'No Test distribution/statistics used for candidate or blend selection': True,
    'Submission row count and ID order checked only for compatibility': True,
}, name='Passed')
display(leakage_audit)
assert leakage_audit.all()

prediction_frame = pd.DataFrame({'ID': test['ID'], 'Target': test_pred33})
submission = sample_submission[['ID']].merge(prediction_frame, on='ID', how='left', validate='one_to_one')
assert submission['Target'].notna().all()
assert len(submission) == len(sample_submission)
assert sample_submission['ID'].equals(submission['ID'])

output_path = SUBMISSION_DIR / '33_row_mod_fine_ensemble_submission.csv'
submission.to_csv(output_path, index=False)
print(f'Saved: {output_path}')
display(submission.head())

result = {
    'create_submission': True,
    'selected_name': selected_name,
    'selected_oof_improvement_vs_28': float(rmse(audit['Target'], audit['Pred28']) - rmse(audit['Target'], oof33)),
    'fold2_improvement': float(selected['Fold2_Improvement']),
    'fold3_improvement': float(selected['Fold3_Improvement']),
    'mean_abs_test_move_vs_28': float(np.mean(np.abs(move))),
    'submission_path': str(output_path),
}
print(result)

28 baseline reproduced from leakage-safe notebook                                 True
Candidate specs evaluated using Train OOF only                                    True
Blend weights selected using Train OOF only                                       True
Validation fold gate thresholds computed only from earlier OOF folds              True
Validation fold residual maps fitted only on earlier OOF folds                    True
Final Test predictions generated by Train-fitted deterministic transforms only    True
No Test target/sample_submission target used                                      True
No Test distribution/statistics used for candidate or blend selection             True
Submission row count and ID order checked only for compatibility                  True
Name: Passed, dtype: bool

Saved: /Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/33_row_mod_fine_ensemble_submission.csv

        ID        Target
0  TR_2427 37,012.275652
1  TR_0028 48,263.403081
2  TR_1461 29,180.383548
3  TR_1977 47,550.036373
4  TR_2351 46,916.430350

{'create_submission': True, 'selected_name': 'blend(0.65*Row_Mod_7|high_hist_gap_q60|p20|a0.32+0.35*Row_Mod_7|all|p20|a0.32)', 'selected_oof_improvement_vs_28': 1.4318195832311176, 'fold2_improvement': 0.07149977054905321, 'fold3_improvement': 4.202300479707901, 'mean_abs_test_move_vs_28': 52.560886172040675, 'submission_path': '/Users/joyeojin/10_Dev/11_Projects/korea-apartment-price-prediction/submissions/33_row_mod_fine_ensemble_submission.csv'}